import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

export function resourceOf(operation) {
  const parts = operation.id.split('.');
  if (parts[0] === 'beta') return parts[1];
  if (['files', 'models', 'skills'].includes(parts[0])) return parts[0];
  if (parts[0] === 'documented') {
    return parts[1] === 'organizationTunnels' ? 'tunnels' : parts[1];
  }
  throw new Error(`Unsupported operation namespace ${operation.id}`);
}

export function surfaceFixture(anchor) {
  const accesses = anchor.operations.map(({ id }) => `  client.${id},`).join('\n');
  return `// Generated by src/cli.mjs. Do not edit.\n`
    + `import Anthropic from '${anchor.module}';\n\n`
    + `const client = new Anthropic();\n`
    + `type Callable = (...args: never[]) => unknown;\n`
    + `// Every discovered operation must remain present and callable in this\n`
    + `// exact SDK anchor. Method invocation behavior is covered separately.\n`
    + `void ([\n${accesses}\n] satisfies readonly Callable[]);\n`;
}

export function operationCoverage({
  extracted,
  documentedRoutes,
  config,
  repoRoot,
  readText = (target) => fs.readFileSync(target, 'utf8'),
}) {
  assert.equal(config.schema_version, 1, 'unsupported coverage config schema');
  const knownResources = new Set(Object.keys(config.resources));
  const current = extracted.find(({ role }) => role === 'current_oracle');
  assert.ok(current, 'current oracle is required for operation coverage');
  const operations = [...current.operations, ...documentedRoutes];
  const ids = new Set();

  return operations.map((operation) => {
    assert.ok(!ids.has(operation.id), `duplicate covered operation ${operation.id}`);
    ids.add(operation.id);
    const resource = resourceOf(operation);
    assert.ok(knownResources.has(resource), `${operation.id} has no resource coverage owner`);
    const rustBehavior = config.resources[resource].rust_behavior;
    const source = readText(path.join(repoRoot, rustBehavior));
    assert.match(
      source,
      /#\[(?:(?:tokio::)?test)(?:\([^]*?\))?\]/u,
      `${rustBehavior} contains no behavior tests`,
    );
    const sdkAnchors = extracted
      .filter(({ operations: anchorOperations }) =>
        anchorOperations.some(({ id }) => id === operation.id))
      .map(({ id }) => id);
    const sdkTransport = !operation.id.startsWith('documented.')
      ? {
          case_id: `${operation.id}.transport.current`,
          owner: 'packages/managed-sdk-oracle/test/sdk-wire-lifecycle.test.ts',
        }
      : { not_applicable: 'sdk_absent_documented_route' };
    return {
      id: operation.id,
      method: operation.method,
      path: operation.path,
      betas: operation.betas ?? [],
      ...(operation.transport_query ? { transport_query: operation.transport_query } : {}),
      resource,
      sdk_anchors: sdkAnchors,
      evidence: {
        deployed_route_semantics: {
          case_id: `${operation.id}.deployed.actual-reference`,
          owner: 'packages/managed-sdk-oracle/src/conformance/deployed-sweep.mjs',
        },
        route_inventory: 'scripts/ci/_managed_protocol_boundary.py',
        rust_behavior: rustBehavior,
        sdk_transport: sdkTransport,
        sdk_surface_compile: sdkAnchors.map(
          (id) => `packages/managed-sdk-oracle/fixtures/generated/${id}.ts`,
        ),
      },
    };
  });
}
