import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

// One resource-level process-replacement owner complements the per-operation
// transport/behavior owners below. Attaching this evidence to every operation
// in the bounded context does not claim that every mutation is replayed; it
// proves that the resource's public identity and durable projection survive a
// fresh process. Stateless SDK helpers (Webhooks) are outside the HTTP operation
// ledger and therefore correctly absent from this map.
export const RESOURCE_RESTART_EVIDENCE = Object.freeze({
  agents: Object.freeze({
    case_id: 'public_management_projections_survive_process_replacement',
    owner: 'e2e/management_persistence_e2e.mjs',
  }),
  deploymentRuns: Object.freeze({
    case_id: 'deployment_run_survives_process_replacement',
    owner: 'e2e/management_persistence_e2e.mjs',
  }),
  deployments: Object.freeze({
    case_id: 'deployment_run_survives_process_replacement',
    owner: 'e2e/management_persistence_e2e.mjs',
  }),
  dreams: Object.freeze({
    case_id: 'official_sdk_dream_restart_interleaving',
    owner: 'e2e/managed_dream_restart_sdk_e2e.ts',
  }),
  environments: Object.freeze({
    case_id: 'environment_work_survives_process_replacement',
    owner: 'e2e/management_env_work_persistence_e2e.mjs',
  }),
  files: Object.freeze({
    case_id: 'python_sdk_resource_recovery',
    owner: 'e2e/conformance/managed_python_sdk_runtime_e2e.py',
  }),
  memoryStores: Object.freeze({
    case_id: 'memory_store_survives_process_replacement',
    owner: 'e2e/managed_memory_store_durable_e2e.mjs',
  }),
  models: Object.freeze({
    case_id: 'public_management_projections_survive_process_replacement',
    owner: 'e2e/management_persistence_e2e.mjs',
  }),
  sessions: Object.freeze({
    case_id: 'python_sdk_resource_recovery',
    owner: 'e2e/conformance/managed_python_sdk_runtime_e2e.py',
  }),
  skills: Object.freeze({
    case_id: 'skill_store_survives_process_replacement',
    owner: 'e2e/managed_skill_store_durable_e2e.mjs',
  }),
  tunnels: Object.freeze({
    case_id: 'active_tunnel_and_rotated_secret_survive_process_replacement',
    owner: 'packages/managed-sdk-oracle/src/conformance/recovery.mjs',
  }),
  userProfiles: Object.freeze({
    case_id: 'public_management_projections_survive_process_replacement',
    owner: 'e2e/management_persistence_e2e.mjs',
  }),
  vaults: Object.freeze({
    case_id: 'public_management_projections_survive_process_replacement',
    owner: 'e2e/management_persistence_e2e.mjs',
  }),
});

export function resourceOf(operation) {
  const parts = operation.id.split('.');
  if (parts[0] === 'beta') return parts[1];
  if (['files', 'models', 'skills'].includes(parts[0])) return parts[0];
  if (parts[0] === 'documented') {
    return parts[1] === 'organizationTunnels' ? 'tunnels' : parts[1];
  }
  throw new Error(`Unsupported operation namespace ${operation.id}`);
}

export function surfaceFixture(anchor) {
  const accesses = anchor.operations.map(({ id }) => `  client.${id},`).join('\n');
  return `// Generated by src/cli.mjs. Do not edit.\n`
    + `import Anthropic from '${anchor.module}';\n\n`
    + `const client = new Anthropic();\n`
    + `type Callable = (...args: never[]) => unknown;\n`
    + `// Every discovered operation must remain present and callable in this\n`
    + `// exact SDK anchor. Method invocation behavior is covered separately.\n`
    + `void ([\n${accesses}\n] satisfies readonly Callable[]);\n`;
}

export function operationCoverage({
  extracted,
  documentedRoutes,
  config,
  repoRoot,
  readText = (target) => fs.readFileSync(target, 'utf8'),
}) {
  assert.equal(config.schema_version, 2, 'unsupported coverage config schema');
  const knownResources = new Set(Object.keys(config.resources));
  for (const resource of knownResources) {
    assert.ok(
      RESOURCE_RESTART_EVIDENCE[resource],
      `${resource} has no process-replacement owner`,
    );
  }
  const current = extracted.find(({ role }) => role === 'current_oracle');
  assert.ok(current, 'current oracle is required for operation coverage');
  const operations = [...current.operations, ...documentedRoutes];
  const ids = new Set();
  const matchedPatterns = new Set();

  const matches = (pattern, id) => pattern.endsWith('*')
    ? id.startsWith(pattern.slice(0, -1))
    : id === pattern;
  const escapeRegex = (value) => value.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&');
  const behaviorSources = new Map();
  const behaviorExists = ({ path: owner, test: caseId }) => {
    const source = behaviorSources.get(owner)
      ?? readText(path.join(repoRoot, owner));
    behaviorSources.set(owner, source);
    const testFunction = new RegExp(
      String.raw`#\[(?:(?:tokio::)?test)(?:\([^]*?\))?\]\s*`
        + String.raw`(?:#\[[^\]]+\]\s*)*(?:async\s+)?fn\s+${escapeRegex(caseId)}\s*\(`,
      'u',
    );
    assert.match(source, testFunction, `${owner} contains no behavior test ${caseId}`);
    const testIndex = source.search(testFunction);
    const design = source.slice(Math.max(0, testIndex - 4_000), testIndex);
    assert.match(
      design,
      new RegExp(String.raw`Test design:\s*${escapeRegex(caseId)}\b`, 'u'),
      `${owner} behavior test ${caseId} has no adjacent named test design`,
    );
    assert.match(
      design,
      /Cause\/effect graph:/u,
      `${owner} behavior test ${caseId} has no cause/effect graph`,
    );
    assert.match(
      design,
      /Decision table:/u,
      `${owner} behavior test ${caseId} has no decision table`,
    );
  };

  const rows = operations.map((operation) => {
    assert.ok(!ids.has(operation.id), `duplicate covered operation ${operation.id}`);
    ids.add(operation.id);
    const resource = resourceOf(operation);
    assert.ok(knownResources.has(resource), `${operation.id} has no resource coverage owner`);
    const cases = config.resources[resource].rust_behavior_cases;
    assert.ok(Array.isArray(cases) && cases.length > 0, `${resource} has no behavior cases`);
    const owners = cases.filter((candidate) => candidate.operations.some((pattern) => {
      const hit = matches(pattern, operation.id);
      if (hit) matchedPatterns.add(`${resource}\0${candidate.test}\0${pattern}`);
      return hit;
    }));
    assert.equal(
      owners.length,
      1,
      `${operation.id} must have exactly one Rust behavior case; found ${owners.length}`,
    );
    const rustBehavior = owners[0];
    behaviorExists(rustBehavior);
    const sdkAnchors = extracted
      .filter(({ operations: anchorOperations }) =>
        anchorOperations.some(({ id }) => id === operation.id))
      .map(({ id }) => id);
    const sdkTransport = !operation.id.startsWith('documented.')
      ? {
          case_id: `${operation.id}.transport.current`,
          owner: 'packages/managed-sdk-oracle/test/sdk-wire-lifecycle.test.ts',
        }
      : { not_applicable: 'sdk_absent_documented_route' };
    return {
      id: operation.id,
      method: operation.method,
      path: operation.path,
      betas: operation.betas ?? [],
      ...(operation.transport_query ? { transport_query: operation.transport_query } : {}),
      resource,
      sdk_anchors: sdkAnchors,
      evidence: {
        local_route_boundary: {
          case_id: `${operation.id}.local.real-process-boundary`,
          owner: 'e2e/conformance/managed_local_operation_sweep_e2e.mjs',
        },
        deployed_route_semantics: {
          case_id: `${operation.id}.deployed.actual-reference`,
          owner: 'packages/managed-sdk-oracle/src/conformance/deployed-sweep.mjs',
        },
        route_inventory: 'scripts/ci/_managed_protocol_boundary.py',
        resource_restart_semantics: RESOURCE_RESTART_EVIDENCE[resource],
        rust_behavior: {
          case_id: rustBehavior.test,
          owner: rustBehavior.path,
        },
        sdk_transport: sdkTransport,
        sdk_surface_compile: sdkAnchors.map(
          (id) => `packages/managed-sdk-oracle/fixtures/generated/${id}.ts`,
        ),
      },
    };
  });

  for (const [resource, { rust_behavior_cases: cases }] of Object.entries(config.resources)) {
    for (const behaviorCase of cases) {
      assert.ok(
        Array.isArray(behaviorCase.operations) && behaviorCase.operations.length > 0,
        `${resource}.${behaviorCase.test} has no operation patterns`,
      );
      behaviorExists(behaviorCase);
      for (const pattern of behaviorCase.operations) {
        assert.ok(
          matchedPatterns.has(`${resource}\0${behaviorCase.test}\0${pattern}`),
          `${resource}.${behaviorCase.test} has dead operation pattern ${pattern}`,
        );
      }
    }
  }
  return rows;
}
