//! Emit JSON Schema for the admin config-plane DTOs to stdout (ADR-0043). This is
//! the SSOT the TS contract is generated from (see `scripts/contract/
//! generate-contracts.sh`), mirroring oversight-next's `export_schemas`.
//!
//! ```sh
//! cargo run -p awaken-admin-config-api --features schema --example export_schemas
//! ```

use schemars::schema_for;
use serde_json::{Map, Value, json};

fn main() {
    let mut defs: Map<String, Value> = Map::new();
    macro_rules! add {
        ($name:literal, $ty:ty) => {
            defs.insert(
                $name.to_string(),
                serde_json::to_value(schema_for!($ty)).expect("schema serializes"),
            );
        };
    }

    // Model-catalog domain.
    add!("Provider", awaken_model_catalog::Provider);
    add!("ProtocolEndpoint", awaken_model_catalog::ProtocolEndpoint);
    add!("Offering", awaken_model_catalog::Offering);
    add!("ModelApiCompat", awaken_model_catalog::ModelApiCompat);
    add!("ProviderCatalog", awaken_model_catalog::ProviderCatalog);

    // Credential domain (secret-free projections only).
    add!("CredentialSource", awaken_credential_vault::CredentialSource);
    add!("CredentialBinding", awaken_credential_vault::CredentialBinding);
    add!("CredentialKind", awaken_credential_vault::CredentialKind);
    add!("CredentialStatus", awaken_credential_vault::CredentialStatus);
    // Credential pools (the `OneOfCredentialPool` binding's members).
    add!("CredentialPoolId", awaken_credential_vault::CredentialPoolId);
    add!("CredentialPool", awaken_credential_vault::CredentialPool);
    add!(
        "CredentialPoolMember",
        awaken_credential_vault::CredentialPoolMember
    );

    // Resolver output (the admin `inference/resolve` dry-run result, secret-free).
    add!(
        "ResolvedInferenceView",
        awaken_admin_config_api::ResolvedInferenceView
    );

    let root = json!({
        "$comment": "GENERATED by awaken-admin-config-api export_schemas; do not edit.",
        "version": awaken_admin_config_api::API_VERSION,
        "schemas": Value::Object(defs),
    });
    println!(
        "{}",
        serde_json::to_string_pretty(&root).expect("root serializes")
    );
}
