import assert from 'node:assert/strict';
import test from 'node:test';

import { loadConformanceClients } from '../src/conformance/clients.mjs';

const clients = await loadConformanceClients();
const managedBetas = ['managed-agents-2026-04-01'];
const baseURL = 'https://managed.invalid';

function json(body, status = 200, headers = {}) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'content-type': 'application/json', ...headers },
  });
}

function errorBody(kind, status) {
  return { type: 'error', error: { type: kind, message: `status ${status}` } };
}

const errorCases = [
  [400, 'invalid_request_error', 'BadRequestError'],
  [401, 'authentication_error', 'AuthenticationError'],
  [403, 'permission_error', 'PermissionDeniedError'],
  [404, 'not_found_error', 'NotFoundError'],
  [408, 'request_timeout', 'APIError'],
  [409, 'conflict_error', 'ConflictError'],
  [413, 'request_too_large', 'APIError'],
  [422, 'invalid_request_error', 'UnprocessableEntityError'],
  [429, 'rate_limit_error', 'RateLimitError'],
  [500, 'api_error', 'InternalServerError'],
  [529, 'overloaded_error', 'InternalServerError'],
];

for (const { version, Client } of clients) {
  test(`${version}: exact Managed error taxonomy and headers survive the SDK`, async () => {
    // Equivalence partition: every status family generated by the official
    // SDK, including the otherwise easy-to-miss 413/422/529 boundaries.
    // C1 canonical envelope+headers and C2 maxRetries=0 produce E1 the exact
    // SDK subclass, E2 unchanged status/type/message/request/workspace ids,
    // and E3 one request. A proxy body, wrong status, or accidental retry fails.
    for (const [status, kind, className] of errorCases) {
      let attempts = 0;
      const client = new Client({
        apiKey: 'transport-only', // awaken-allow: secret
        baseURL,
        maxRetries: 0,
        fetch: async () => {
          attempts += 1;
          return json(errorBody(kind, status), status, {
            'request-id': `request-${status}`,
            'anthropic-workspace-id': `workspace-${status}`,
          });
        },
      });
      await assert.rejects(
        () => client.beta.sessions.retrieve('missing'),
        (error) => {
          assert.equal(error.constructor, Client[className], `${status}: exact ${className}`);
          assert.equal(error.status, status, `${status}: status`);
          assert.equal(error.type, kind, `${status}: promoted error type`);
          assert.equal(error.error.type, 'error', `${status}: envelope`);
          assert.equal(error.error.error.type, kind, `${status}: nested kind`);
          assert.equal(error.error.error.message, `status ${status}`, `${status}: message`);
          assert.equal(error.requestID, `request-${status}`, `${status}: request identity`);
          assert.equal(
            error.headers.get('anthropic-workspace-id'),
            `workspace-${status}`,
            `${status}: workspace header`,
          );
          if ('workspaceID' in error) {
            assert.equal(error.workspaceID, `workspace-${status}`, `${status}: workspace identity`);
          }
          return true;
        },
      );
      assert.equal(attempts, 1, `${status}: disabled retry`);
    }
  });

  test(`${version}: retry decision table is owned entirely by the SDK`, async () => {
    // Decision table from the official transport: 408/409/429/5xx retry;
    // ordinary 4xx do not; x-should-retry is authoritative in both directions.
    // Each retryable case fails twice then succeeds, proving the exact bound.
    // retry-after-ms=0 keeps this a deterministic policy test rather than time.
    const cases = [
      [400, false, undefined],
      [408, true, undefined],
      [409, true, undefined],
      [413, false, undefined],
      [422, false, undefined],
      [429, true, undefined],
      [500, true, undefined],
      [529, true, undefined],
      [400, true, 'true'],
      [500, false, 'false'],
    ];
    for (const [status, retries, override] of cases) {
      let attempts = 0;
      const client = new Client({
        apiKey: 'transport-only', // awaken-allow: secret
        baseURL,
        maxRetries: 2,
        fetch: async () => {
          attempts += 1;
          if (retries && attempts === 3) {
            return json({ data: [], has_more: false, next_page: null });
          }
          return json(errorBody('api_error', status), status, {
            'retry-after-ms': '0',
            ...(override ? { 'x-should-retry': override } : {}),
          });
        },
      });
      if (retries) {
        const page = await client.beta.sessions.list();
        assert.deepEqual(page.data, [], `${status}/${override ?? 'default'}: eventual result`);
      } else {
        await assert.rejects(
          () => client.beta.sessions.list(),
          (error) => error.status === status,
        );
      }
      assert.equal(attempts, retries ? 3 : 1, `${status}/${override ?? 'default'}: attempt bound`);
    }
  });

  test(`${version}: mutation retries preserve the complete command identity`, async () => {
    // Metamorphic relation: one transient response transforms one logical
    // create into two HTTP attempts, but method, URL, body, capability and
    // caller idempotency key remain byte-identical. Only SDK retry telemetry
    // may differ. This prevents a transport upgrade from duplicating a durable
    // command even when the first response is lost after server commit.
    const attempts = [];
    const client = new Client({
      apiKey: 'transport-only', // awaken-allow: secret
      baseURL,
      maxRetries: 1,
      fetch: async (input, init) => {
        const request = new Request(input, init);
        attempts.push({
          method: request.method,
          url: request.url,
          body: await request.clone().text(),
          idempotencyKey: request.headers.get('idempotency-key'),
          betas: request.headers.get('anthropic-beta'),
          version: request.headers.get('anthropic-version'),
          packageVersion: request.headers.get('x-stainless-package-version'),
        });
        return attempts.length === 1
          ? json(errorBody('api_error', 500), 500, { 'retry-after-ms': '0' })
          : json({ id: 'session-retry', type: 'session' });
      },
    });
    const session = await client.beta.sessions.create({
      agent: 'agent-retry',
      environment_id: 'environment-retry',
      title: 'retry identity',
    }, { headers: { 'idempotency-key': 'command-retry' } });
    assert.equal(session.id, 'session-retry');
    assert.equal(attempts.length, 2);
    assert.deepEqual(attempts[1], attempts[0], 'retry preserves every command coordinate');
    assert.deepEqual(JSON.parse(attempts[0].body), {
      agent: 'agent-retry',
      environment_id: 'environment-retry',
      title: 'retry identity',
    });
    assert.equal(attempts[0].idempotencyKey, 'command-retry');
    assert.equal(attempts[0].betas, managedBetas[0]);
    assert.equal(attempts[0].version, '2023-06-01');
    assert.equal(attempts[0].packageVersion, version);
  });

  test(`${version}: paginator follows each opaque cursor exactly once`, async () => {
    // State-transition graph: initial page -> opaque next_page -> terminal
    // page. The SDK must preserve the original query and capability while only
    // adding page=cursor-1, yield both identities in order, and never overlap.
    // This catches cursor renaming, accidental offset semantics, and a loop on
    // the terminal null cursor in every supported/candidate transport.
    const requests = [];
    const client = new Client({
      apiKey: 'transport-only', // awaken-allow: secret
      baseURL,
      maxRetries: 0,
      fetch: async (input, init) => {
        const request = new Request(input, init);
        const url = new URL(request.url);
        requests.push({
          limit: url.searchParams.get('limit'),
          page: url.searchParams.get('page'),
          betas: request.headers.get('anthropic-beta'),
        });
        return url.searchParams.get('page') === 'cursor-1'
          ? json({ data: [{ id: 'session-2' }], has_more: false, next_page: null })
          : json({ data: [{ id: 'session-1' }], has_more: true, next_page: 'cursor-1' });
      },
    });
    const ids = [];
    for await (const session of client.beta.sessions.list({ limit: 1 })) ids.push(session.id);
    assert.deepEqual(ids, ['session-1', 'session-2']);
    assert.equal(new Set(ids).size, ids.length);
    assert.deepEqual(requests, [
      { limit: '1', page: null, betas: managedBetas[0] },
      { limit: '1', page: 'cursor-1', betas: managedBetas[0] },
    ]);
  });

  test(`${version}: caller abort is classified and never retried`, async () => {
    // Fault injection: an AbortError crosses the fetch boundary. It must become
    // the official APIUserAbortError after exactly one attempt; treating it as
    // a transient connection fault would execute work after caller cancellation.
    let attempts = 0;
    const controller = new AbortController();
    const client = new Client({
      apiKey: 'transport-only', // awaken-allow: secret
      baseURL,
      maxRetries: 2,
      fetch: async () => {
        attempts += 1;
        controller.abort();
        throw new DOMException('cancelled by caller', 'AbortError');
      },
    });
    await assert.rejects(
      () => client.beta.sessions.list({}, { signal: controller.signal }),
      (error) => error.constructor === Client.APIUserAbortError,
    );
    assert.equal(attempts, 1);
  });

  test(`${version}: middleware preserves the canonical Managed retry chain`, async () => {
    // Call-chain graph:
    // generated Managed operation -> canonical request/auth/capabilities ->
    // outer middleware -> inner middleware -> fetch -> parsed clone -> reverse
    // middleware unwind -> SDK retry/decoder. C1=first response 500 and C2=
    // second response 200; E1=both attempts traverse the complete chain in
    // order, E2=middleware sees retry identity and the Managed selector, E3=
    // parsing through ctx.parse never consumes the response, and E4=the SDK
    // still decodes the final page. C3=ordinary middleware exception; E5=the
    // exact exception escapes after one middleware entry and zero fetches.
    //
    // Decision table:
    // | middleware outcome | maxRetries | fetches | caller result            |
    // | 500 then 200        | 1          | 2       | decoded Managed page     |
    // | ordinary exception | 2          | 0       | same exception, no retry |
    const events = [];
    const parsed = [];
    let attempts = 0;
    const middleware = [
      async (request, next, context) => {
        const retry = request.headers.get('x-stainless-retry-count');
        events.push(`outer-before:${retry}`);
        assert.equal(context.options?.method, 'get');
        assert.equal(context.options?.path, '/v1/sessions?beta=true');
        assert.equal(request.headers.get('anthropic-beta'), managedBetas[0]);
        assert.equal(request.headers.get('x-api-key'), 'middleware-auth');
        const headers = new Headers(request.headers);
        headers.set('x-middleware-attempt', retry);
        const response = await next({ ...request, headers });
        const body = await context.parse(response);
        parsed.push({ layer: 'outer', retry, body });
        events.push(`outer-after:${retry}:${response.status}`);
        return response;
      },
      async (request, next, context) => {
        const retry = request.headers.get('x-stainless-retry-count');
        events.push(`inner-before:${retry}`);
        assert.equal(request.headers.get('x-middleware-attempt'), retry);
        const response = await next(request);
        const body = await context.parse(response);
        parsed.push({ layer: 'inner', retry, body });
        events.push(`inner-after:${retry}:${response.status}`);
        return response;
      },
    ];
    const client = new Client({
      apiKey: 'middleware-auth', // awaken-allow: secret
      baseURL,
      maxRetries: 1,
      middleware,
      fetch: async (_input, init) => {
        attempts += 1;
        const retry = new Headers(init?.headers).get('x-stainless-retry-count');
        events.push(`fetch:${retry}`);
        return attempts === 1
          ? json(errorBody('api_error', 500), 500, { 'retry-after-ms': '0' })
          : json({ data: [], has_more: false, next_page: null });
      },
    });
    assert.deepEqual((await client.beta.sessions.list()).data, []);
    assert.equal(attempts, 2);
    assert.deepEqual(events, [
      'outer-before:0',
      'inner-before:0',
      'fetch:0',
      'inner-after:0:500',
      'outer-after:0:500',
      'outer-before:1',
      'inner-before:1',
      'fetch:1',
      'inner-after:1:200',
      'outer-after:1:200',
    ]);
    assert.equal(parsed.length, 4);
    assert.strictEqual(parsed[0].body, parsed[1].body, 'one response parse is cached across layers');
    assert.strictEqual(parsed[2].body, parsed[3].body, 'retry response parse is cached across layers');
    assert.equal(parsed[0].body.error.type, 'api_error');
    assert.deepEqual(parsed[2].body.data, []);

    const sentinel = new Error('middleware policy rejected request');
    let rejectedEntries = 0;
    let rejectedFetches = 0;
    const rejecting = new Client({
      apiKey: 'middleware-auth', // awaken-allow: secret
      baseURL,
      maxRetries: 2,
      middleware: [async () => {
        rejectedEntries += 1;
        throw sentinel;
      }],
      fetch: async () => {
        rejectedFetches += 1;
        return json({ data: [], has_more: false, next_page: null });
      },
    });
    await assert.rejects(() => rejecting.beta.sessions.list(), (error) => error === sentinel);
    assert.equal(rejectedEntries, 1);
    assert.equal(rejectedFetches, 0);
  });

  test(`${version}: connection faults and SDK timeouts retain distinct retry semantics`, async () => {
    // Cause/effect graph:
    // C1 fetch rejects with a connection fault before any HTTP response;
    // C2 maxRetries=0 or 1; C3 the retry's second attempt returns a valid
    // Managed page; C4 the SDK deadline aborts an otherwise pending fetch.
    // Effects: C1+C2(0) -> exact APIConnectionError after one attempt;
    // C1+C2(1)+C3 -> exactly two attempts and one decoded page; C4+C2(0) ->
    // exact APIConnectionTimeoutError after one attempt. A caller
    // abort remains separately owned above and must never be normalized into
    // either transport outcome.
    //
    // Decision table:
    // | cause                 | retries | terminal result                  |
    // | connection            | 0       | APIConnectionError, once         |
    // | connection, then 200  | 1       | decoded page, two attempts       |
    // | SDK deadline          | 0       | APIConnectionTimeoutError, once  |
    // | caller abort          | any     | APIUserAbortError, once (above)  |
    let failedConnectionAttempts = 0;
    const disconnected = new Client({
      apiKey: 'transport-only', // awaken-allow: secret
      baseURL,
      maxRetries: 0,
      fetch: async () => {
        failedConnectionAttempts += 1;
        throw new TypeError('connection closed');
      },
    });
    await assert.rejects(
      () => disconnected.beta.sessions.list(),
      (error) => error.constructor === Client.APIConnectionError
        && error.cause?.constructor === TypeError,
    );
    assert.equal(failedConnectionAttempts, 1, 'a disabled connection retry issues one attempt');

    let connectionAttempts = 0;
    const reconnecting = new Client({
      apiKey: 'transport-only', // awaken-allow: secret
      baseURL,
      maxRetries: 1,
      fetch: async () => {
        connectionAttempts += 1;
        if (connectionAttempts === 1) throw new TypeError('connection closed');
        return json({ data: [], has_more: false, next_page: null });
      },
    });
    const page = await reconnecting.beta.sessions.list();
    assert.deepEqual(page.data, [], 'connection retry decodes the eventual response');
    assert.equal(connectionAttempts, 2, 'connection retry uses the exact configured bound');

    let timeoutAttempts = 0;
    const timingOut = new Client({
      apiKey: 'transport-only', // awaken-allow: secret
      baseURL,
      maxRetries: 0,
      fetch: async (_input, init) => new Promise((_resolve, reject) => {
        timeoutAttempts += 1;
        const fail = () => reject(new DOMException('SDK deadline elapsed', 'AbortError'));
        if (init?.signal?.aborted) fail();
        else init?.signal?.addEventListener('abort', fail, { once: true });
      }),
    });
    await assert.rejects(
      () => timingOut.beta.sessions.list({}, { timeout: 20 }),
      (error) => error.constructor === Client.APIConnectionTimeoutError,
    );
    assert.equal(timeoutAttempts, 1, 'a disabled timeout retry cannot issue later work');
  });

  test(`${version}: dynamic credentials preserve precedence, scope, and one forced refresh`, async () => {
    // Authentication state machine:
    // S0 provider unresolved -> S1 cached stale Bearer -> 401 -> S2 forced
    // provider refresh -> S3 fresh Bearer -> 200. An API key instead enters
    // S4 static auth and must never resolve the provider. Although the current
    // TypeScript declaration comment says a provider precedes authToken, every
    // admitted executable package gives both explicit static forms precedence;
    // this behavioral change point must be reviewed if upstream reconciles it.
    //
    // Decision table:
    // | apiKey | authToken | provider | first result | requests/provider calls |
    // | absent | absent    | present  | 401 then 200 | 2 / [normal, forced]    |
    // | present| absent    | present  | 200          | 1 / 0                   |
    // | absent | present   | present  | 200          | 1 / 0                   |
    //
    // The OAuth capability is part of credential transport, while the Managed
    // capability remains the operation selector; both must survive refresh
    // exactly once without leaking the shadowed static token.
    const providerCalls = [];
    const requests = [];
    const credentials = async (options) => {
      providerCalls.push(options ?? null);
      return {
        token: providerCalls.length === 1 ? 'provider-stale' : 'provider-fresh',
        expiresAt: null,
      };
    };
    const refreshing = new Client({
      apiKey: null,
      authToken: null,
      credentials,
      baseURL,
      maxRetries: 1,
      fetch: async (input, init) => {
        const request = new Request(input, init);
        requests.push(request);
        return requests.length === 1
          ? json(errorBody('authentication_error', 401), 401, { 'retry-after-ms': '0' })
          : json({ data: [], has_more: false, next_page: null });
      },
    });
    assert.deepEqual((await refreshing.beta.sessions.list()).data, []);
    assert.deepEqual(providerCalls, [null, { forceRefresh: true }]);
    assert.equal(requests.length, 2, 'one rejected token permits one refreshed attempt');
    assert.deepEqual(
      requests.map((request) => request.headers.get('authorization')),
      ['Bearer provider-stale', 'Bearer provider-fresh'],
    );
    assert.ok(requests.every((request) => request.headers.get('x-api-key') === null));
    assert.deepEqual(
      requests.map((request) => request.headers.get('x-stainless-retry-count')),
      ['0', '1'],
    );
    assert.ok(requests.every((request) => {
      const betas = request.headers.get('anthropic-beta')?.split(',').map((item) => item.trim()).sort();
      return JSON.stringify(betas) === JSON.stringify([
        'managed-agents-2026-04-01',
        'oauth-2025-04-20',
      ]);
    }), 'provider auth composes the Managed and OAuth capabilities exactly');

    for (const staticKind of ['apiKey', 'authToken']) {
      let shadowedProviderCalls = 0;
      let staticRequest;
      const staticClient = new Client({
        apiKey: staticKind === 'apiKey' ? 'static-api' : null, // awaken-allow: secret
        authToken: staticKind === 'authToken' ? 'static-token' : null, // awaken-allow: secret
        credentials: async () => {
          shadowedProviderCalls += 1;
          return { token: 'must-not-be-used', expiresAt: null }; // awaken-allow: secret
        },
        baseURL,
        maxRetries: 0,
        fetch: async (input, init) => {
          staticRequest = new Request(input, init);
          return json({ data: [], has_more: false, next_page: null });
        },
      });
      await staticClient.beta.sessions.list();
      assert.equal(shadowedProviderCalls, 0, `an explicit ${staticKind} never resolves credentials`);
      assert.equal(
        staticRequest.headers.get('x-api-key'),
        staticKind === 'apiKey' ? 'static-api' : null,
      );
      assert.equal(
        staticRequest.headers.get('authorization'),
        staticKind === 'authToken' ? 'Bearer static-token' : null,
      );
      assert.deepEqual(
        staticRequest.headers.get('anthropic-beta')?.split(',').map((item) => item.trim()),
        managedBetas,
        'static auth does not impersonate OAuth transport',
      );
    }
  });
}
