import assert from 'node:assert/strict';
import test from 'node:test';

import { loadConformanceClients } from '../src/conformance/clients.mjs';

const clients = await loadConformanceClients();
const managedBetas = ['managed-agents-2026-04-01'];
const baseURL = 'https://managed.invalid';

function json(body, status = 200, headers = {}) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'content-type': 'application/json', ...headers },
  });
}

function errorBody(kind, status) {
  return { type: 'error', error: { type: kind, message: `status ${status}` } };
}

const errorCases = [
  [400, 'invalid_request_error', 'BadRequestError'],
  [401, 'authentication_error', 'AuthenticationError'],
  [403, 'permission_error', 'PermissionDeniedError'],
  [404, 'not_found_error', 'NotFoundError'],
  [409, 'conflict_error', 'ConflictError'],
  [413, 'request_too_large', 'APIError'],
  [422, 'invalid_request_error', 'UnprocessableEntityError'],
  [429, 'rate_limit_error', 'RateLimitError'],
  [500, 'api_error', 'InternalServerError'],
  [529, 'overloaded_error', 'InternalServerError'],
];

for (const { version, Client } of clients) {
  test(`${version}: exact Managed error taxonomy and headers survive the SDK`, async () => {
    // Equivalence partition: every status family generated by the official
    // SDK, including the otherwise easy-to-miss 413/422/529 boundaries.
    // C1 canonical envelope+headers and C2 maxRetries=0 produce E1 the exact
    // SDK subclass, E2 unchanged status/type/message/request/workspace ids,
    // and E3 one request. A proxy body, wrong status, or accidental retry fails.
    for (const [status, kind, className] of errorCases) {
      let attempts = 0;
      const client = new Client({
        apiKey: 'transport-only', // awaken-allow: secret
        baseURL,
        maxRetries: 0,
        fetch: async () => {
          attempts += 1;
          return json(errorBody(kind, status), status, {
            'request-id': `request-${status}`,
            'anthropic-workspace-id': `workspace-${status}`,
          });
        },
      });
      await assert.rejects(
        () => client.beta.sessions.retrieve('missing'),
        (error) => {
          assert.equal(error.constructor, Client[className], `${status}: exact ${className}`);
          assert.equal(error.status, status, `${status}: status`);
          assert.equal(error.type, kind, `${status}: promoted error type`);
          assert.equal(error.error.type, 'error', `${status}: envelope`);
          assert.equal(error.error.error.type, kind, `${status}: nested kind`);
          assert.equal(error.error.error.message, `status ${status}`, `${status}: message`);
          assert.equal(error.requestID, `request-${status}`, `${status}: request identity`);
          assert.equal(
            error.headers.get('anthropic-workspace-id'),
            `workspace-${status}`,
            `${status}: workspace header`,
          );
          if ('workspaceID' in error) {
            assert.equal(error.workspaceID, `workspace-${status}`, `${status}: workspace identity`);
          }
          return true;
        },
      );
      assert.equal(attempts, 1, `${status}: disabled retry`);
    }
  });

  test(`${version}: retry decision table is owned entirely by the SDK`, async () => {
    // Decision table from the official transport: 408/409/429/5xx retry;
    // ordinary 4xx do not; x-should-retry is authoritative in both directions.
    // Each retryable case fails twice then succeeds, proving the exact bound.
    // retry-after-ms=0 keeps this a deterministic policy test rather than time.
    const cases = [
      [400, false, undefined],
      [408, true, undefined],
      [409, true, undefined],
      [413, false, undefined],
      [422, false, undefined],
      [429, true, undefined],
      [500, true, undefined],
      [529, true, undefined],
      [400, true, 'true'],
      [500, false, 'false'],
    ];
    for (const [status, retries, override] of cases) {
      let attempts = 0;
      const client = new Client({
        apiKey: 'transport-only', // awaken-allow: secret
        baseURL,
        maxRetries: 2,
        fetch: async () => {
          attempts += 1;
          if (retries && attempts === 3) {
            return json({ data: [], has_more: false, next_page: null });
          }
          return json(errorBody('api_error', status), status, {
            'retry-after-ms': '0',
            ...(override ? { 'x-should-retry': override } : {}),
          });
        },
      });
      if (retries) {
        const page = await client.beta.sessions.list();
        assert.deepEqual(page.data, [], `${status}/${override ?? 'default'}: eventual result`);
      } else {
        await assert.rejects(
          () => client.beta.sessions.list(),
          (error) => error.status === status,
        );
      }
      assert.equal(attempts, retries ? 3 : 1, `${status}/${override ?? 'default'}: attempt bound`);
    }
  });

  test(`${version}: mutation retries preserve the complete command identity`, async () => {
    // Metamorphic relation: one transient response transforms one logical
    // create into two HTTP attempts, but method, URL, body, capability and
    // caller idempotency key remain byte-identical. Only SDK retry telemetry
    // may differ. This prevents a transport upgrade from duplicating a durable
    // command even when the first response is lost after server commit.
    const attempts = [];
    const client = new Client({
      apiKey: 'transport-only', // awaken-allow: secret
      baseURL,
      maxRetries: 1,
      fetch: async (input, init) => {
        const request = new Request(input, init);
        attempts.push({
          method: request.method,
          url: request.url,
          body: await request.clone().text(),
          idempotencyKey: request.headers.get('idempotency-key'),
          betas: request.headers.get('anthropic-beta'),
          version: request.headers.get('anthropic-version'),
          packageVersion: request.headers.get('x-stainless-package-version'),
        });
        return attempts.length === 1
          ? json(errorBody('api_error', 500), 500, { 'retry-after-ms': '0' })
          : json({ id: 'session-retry', type: 'session' });
      },
    });
    const session = await client.beta.sessions.create({
      agent: 'agent-retry',
      environment_id: 'environment-retry',
      title: 'retry identity',
    }, { headers: { 'idempotency-key': 'command-retry' } });
    assert.equal(session.id, 'session-retry');
    assert.equal(attempts.length, 2);
    assert.deepEqual(attempts[1], attempts[0], 'retry preserves every command coordinate');
    assert.deepEqual(JSON.parse(attempts[0].body), {
      agent: 'agent-retry',
      environment_id: 'environment-retry',
      title: 'retry identity',
    });
    assert.equal(attempts[0].idempotencyKey, 'command-retry');
    assert.equal(attempts[0].betas, managedBetas[0]);
    assert.equal(attempts[0].version, '2023-06-01');
    assert.equal(attempts[0].packageVersion, version);
  });

  test(`${version}: paginator follows each opaque cursor exactly once`, async () => {
    // State-transition graph: initial page -> opaque next_page -> terminal
    // page. The SDK must preserve the original query and capability while only
    // adding page=cursor-1, yield both identities in order, and never overlap.
    // This catches cursor renaming, accidental offset semantics, and a loop on
    // the terminal null cursor in every supported/candidate transport.
    const requests = [];
    const client = new Client({
      apiKey: 'transport-only', // awaken-allow: secret
      baseURL,
      maxRetries: 0,
      fetch: async (input, init) => {
        const request = new Request(input, init);
        const url = new URL(request.url);
        requests.push({
          limit: url.searchParams.get('limit'),
          page: url.searchParams.get('page'),
          betas: request.headers.get('anthropic-beta'),
        });
        return url.searchParams.get('page') === 'cursor-1'
          ? json({ data: [{ id: 'session-2' }], has_more: false, next_page: null })
          : json({ data: [{ id: 'session-1' }], has_more: true, next_page: 'cursor-1' });
      },
    });
    const ids = [];
    for await (const session of client.beta.sessions.list({ limit: 1 })) ids.push(session.id);
    assert.deepEqual(ids, ['session-1', 'session-2']);
    assert.equal(new Set(ids).size, ids.length);
    assert.deepEqual(requests, [
      { limit: '1', page: null, betas: managedBetas[0] },
      { limit: '1', page: 'cursor-1', betas: managedBetas[0] },
    ]);
  });

  test(`${version}: caller abort is classified and never retried`, async () => {
    // Fault injection: an AbortError crosses the fetch boundary. It must become
    // the official APIUserAbortError after exactly one attempt; treating it as
    // a transient connection fault would execute work after caller cancellation.
    let attempts = 0;
    const controller = new AbortController();
    const client = new Client({
      apiKey: 'transport-only', // awaken-allow: secret
      baseURL,
      maxRetries: 2,
      fetch: async () => {
        attempts += 1;
        controller.abort();
        throw new DOMException('cancelled by caller', 'AbortError');
      },
    });
    await assert.rejects(
      () => client.beta.sessions.list({}, { signal: controller.signal }),
      (error) => error.constructor === Client.APIUserAbortError,
    );
    assert.equal(attempts, 1);
  });
}
