apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../bases/postgres
  - resources.yaml
patches:
  - target:
      kind: Deployment
      name: postgres
    patch: |-
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: database-init
          configMap:
            name: adr71-database-init
            defaultMode: 0755
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: database-init
          mountPath: /docker-entrypoint-initdb.d
          readOnly: true
