//! The config-store schema, shared by the Postgres and SQLite backends.
//!
//! One portable [`MigrationBundle`] under the `config` namespace, so it coexists
//! with the runtime's `runtime_*` tables and its own ledger
//! (`config_schema_migrations`) in one database (ADR-0029/ADR-0031).

use awaken_scoped_migration::{Migration, MigrationBundle, MigrationError};

/// Bundle id for the config schema. Scoped so it never collides with the commit
/// or dispatch schemas in a shared database.
pub const BUNDLE_ID: &str = "awaken.config";

const SPECS: [(i64, &str, &str); 4] = [
    (
        1,
        "agent configs: the authoring aggregate, one row per agent id",
        "CREATE TABLE {prefix}_agent (\
            id TEXT PRIMARY KEY, \
            data {json} NOT NULL, \
            created_at {timestamptz} NOT NULL DEFAULT {now})",
    ),
    (
        2,
        "publications: the compiled artifact, content-addressed by fingerprint",
        "CREATE TABLE {prefix}_publication (\
            fingerprint TEXT PRIMARY KEY, \
            agent_id TEXT NOT NULL, \
            state TEXT NOT NULL, \
            record {json} NOT NULL, \
            created_at {timestamptz} NOT NULL DEFAULT {now})",
    ),
    (
        // Tenancy edge aspect (ADR-0051 D2/D4): one opaque owner `scope_id` on the
        // authoring aggregate. Additive with a seeded default so existing rows stay
        // valid; reads filter `WHERE scope_id = ?` and writes are scope-guarded, so
        // a workspace cannot read or clobber another's agent by id.
        3,
        "agent configs: opaque owner scope_id (ADR-0051)",
        "ALTER TABLE {prefix}_agent ADD COLUMN scope_id TEXT NOT NULL DEFAULT 'default'",
    ),
    (
        4,
        "publications: opaque owner scope_id (ADR-0051)",
        "ALTER TABLE {prefix}_publication ADD COLUMN scope_id TEXT NOT NULL DEFAULT 'default'",
    ),
];

/// Build the config-schema migration bundle.
pub fn config_bundle() -> Result<MigrationBundle, MigrationError> {
    let mut migrations = SPECS
        .iter()
        .map(|(version, description, sql)| Migration::new(*version, *description, *sql))
        .collect::<Result<Vec<_>, _>>()?;
    // Deterministic list ordering (ADR-0043 warm-load): the publication list must
    // reload in a deterministic order so "latest publication per agent" is stable.
    // SQLite already has an implicit monotonic `rowid` it orders by; Postgres has
    // none, so `ORDER BY created_at ASC` alone leaves same-instant inserts in an
    // undefined relative order. Give Postgres a monotonic insertion-order `seq`
    // column to break the tie; SQLite keeps its `rowid` (this migration is inert
    // there — a no-op index on the column it already orders by). The two bodies
    // cannot share one portable token template, so this is a per-dialect migration.
    migrations.push(Migration::per_dialect(
        5,
        "publications: monotonic insertion-order tie-break for deterministic warm-load",
        // Postgres: an identity column assigns a strictly increasing value on each
        // insert, so `ORDER BY created_at ASC, seq ASC` is total and deterministic.
        "ALTER TABLE {prefix}_publication ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY",
        // SQLite orders by its built-in `rowid`; nothing to add. A harmless,
        // idempotent index on the existing `created_at` column stands in as an
        // inert body (a migration body may not be blank).
        "CREATE INDEX IF NOT EXISTS {prefix}_publication_created_at_idx \
         ON {prefix}_publication (created_at)",
    )?);
    migrations.push(Migration::new(
        6,
        "agent configs: monotonic generation for atomic compare-and-set",
        "ALTER TABLE {prefix}_agent ADD COLUMN generation BIGINT NOT NULL DEFAULT 1",
    )?);
    migrations.push(Migration::new(
        7,
        "durable management audit keyed by scope and stable call id",
        "CREATE TABLE {prefix}_management_audit (\
            scope_id TEXT NOT NULL, \
            call_id TEXT NOT NULL, \
            record {json} NOT NULL, \
            business_committed BIGINT NOT NULL DEFAULT 0, \
            created_at {timestamptz} NOT NULL DEFAULT {now}, \
            PRIMARY KEY (scope_id, call_id))",
    )?);
    migrations.push(Migration::new(
        8,
        "durable idempotent effects for stores outside the config transaction",
        "CREATE TABLE {prefix}_management_effect (\
            scope_id TEXT NOT NULL, \
            kind TEXT NOT NULL, \
            effect_key TEXT NOT NULL, \
            payload {json} NOT NULL, \
            created_at {timestamptz} NOT NULL DEFAULT {now}, \
            PRIMARY KEY (scope_id, kind, effect_key))",
    )?);
    MigrationBundle::new(BUNDLE_ID, migrations)
}
