//! The config-store schema, shared by the Postgres and SQLite backends.
//!
//! One portable [`MigrationBundle`] under the `config` namespace, so it coexists
//! with the runtime's `runtime_*` tables and its own ledger
//! (`config_schema_migrations`) in one database (ADR-0029/ADR-0031).

use awaken_scoped_migration::{Migration, MigrationBundle, MigrationError};

/// Bundle id for the config schema. Scoped so it never collides with the commit
/// or dispatch schemas in a shared database.
pub const BUNDLE_ID: &str = "awaken.config";

const SPECS: [(i64, &str, &str); 4] = [
    (
        1,
        "agent configs: the authoring aggregate, one row per agent id",
        "CREATE TABLE {prefix}_agent (\
            id TEXT PRIMARY KEY, \
            data {json} NOT NULL, \
            created_at {timestamptz} NOT NULL DEFAULT {now})",
    ),
    (
        2,
        "publications: the compiled artifact, content-addressed by fingerprint",
        "CREATE TABLE {prefix}_publication (\
            fingerprint TEXT PRIMARY KEY, \
            agent_id TEXT NOT NULL, \
            state TEXT NOT NULL, \
            record {json} NOT NULL, \
            created_at {timestamptz} NOT NULL DEFAULT {now})",
    ),
    (
        // Tenancy edge aspect (ADR-0051 D2/D4): one opaque owner `scope_id` on the
        // authoring aggregate. Additive with a seeded default so existing rows stay
        // valid; reads filter `WHERE scope_id = ?` and writes are scope-guarded, so
        // a workspace cannot read or clobber another's agent by id.
        3,
        "agent configs: opaque owner scope_id (ADR-0051)",
        "ALTER TABLE {prefix}_agent ADD COLUMN scope_id TEXT NOT NULL DEFAULT 'default'",
    ),
    (
        4,
        "publications: opaque owner scope_id (ADR-0051)",
        "ALTER TABLE {prefix}_publication ADD COLUMN scope_id TEXT NOT NULL DEFAULT 'default'",
    ),
];

/// Build the config-schema migration bundle.
pub fn config_bundle() -> Result<MigrationBundle, MigrationError> {
    let mut migrations = SPECS
        .iter()
        .map(|(version, description, sql)| Migration::new(*version, *description, *sql))
        .collect::<Result<Vec<_>, _>>()?;
    // Deterministic list ordering (ADR-0043 warm-load): the publication list must
    // reload in a deterministic order so "latest publication per agent" is stable.
    // SQLite already has an implicit monotonic `rowid` it orders by; Postgres has
    // none, so `ORDER BY created_at ASC` alone leaves same-instant inserts in an
    // undefined relative order. Give Postgres a monotonic insertion-order `seq`
    // column to break the tie; SQLite keeps its `rowid` (this migration is inert
    // there — a no-op index on the column it already orders by). The two bodies
    // cannot share one portable token template, so this is a per-dialect migration.
    migrations.push(Migration::per_dialect(
        5,
        "publications: monotonic insertion-order tie-break for deterministic warm-load",
        // Postgres: an identity column assigns a strictly increasing value on each
        // insert, so `ORDER BY created_at ASC, seq ASC` is total and deterministic.
        "ALTER TABLE {prefix}_publication ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY",
        // SQLite orders by its built-in `rowid`; nothing to add. A harmless,
        // idempotent index on the existing `created_at` column stands in as an
        // inert body (a migration body may not be blank).
        "CREATE INDEX {prefix}_publication_created_at_idx \
         ON {prefix}_publication (created_at)",
    )?);
    migrations.push(Migration::new(
        6,
        "agent configs: monotonic generation for atomic compare-and-set",
        "ALTER TABLE {prefix}_agent ADD COLUMN generation BIGINT NOT NULL DEFAULT 1",
    )?);
    migrations.push(Migration::new(
        7,
        "durable management audit keyed by scope and stable call id",
        "CREATE TABLE {prefix}_management_audit (\
            scope_id TEXT NOT NULL, \
            call_id TEXT NOT NULL, \
            record {json} NOT NULL, \
            business_committed BIGINT NOT NULL DEFAULT 0, \
            created_at {timestamptz} NOT NULL DEFAULT {now}, \
            PRIMARY KEY (scope_id, call_id))",
    )?);
    migrations.push(Migration::new(
        8,
        "durable idempotent effects for stores outside the config transaction",
        "CREATE TABLE {prefix}_management_effect (\
            scope_id TEXT NOT NULL, \
            kind TEXT NOT NULL, \
            effect_key TEXT NOT NULL, \
            payload {json} NOT NULL, \
            created_at {timestamptz} NOT NULL DEFAULT {now}, \
            PRIMARY KEY (scope_id, kind, effect_key))",
    )?);
    migrations.push(Migration::per_dialect(
        9,
        "agent configs: immutable revision history for managed Agent versions",
        "CREATE TABLE {prefix}_agent_revision (\
            scope_id TEXT NOT NULL, id TEXT NOT NULL, generation BIGINT NOT NULL, \
            data {json} NOT NULL, created_at {timestamptz} NOT NULL DEFAULT {now}, \
            PRIMARY KEY (scope_id, id, generation)); \
         INSERT INTO {prefix}_agent_revision (scope_id, id, generation, data) \
            SELECT scope_id, id, generation, data FROM {prefix}_agent; \
         CREATE FUNCTION {prefix}_capture_agent_revision() RETURNS TRIGGER AS $$ \
            BEGIN INSERT INTO {prefix}_agent_revision (scope_id, id, generation, data) \
              VALUES (NEW.scope_id, NEW.id, NEW.generation, NEW.data); RETURN NEW; END; \
            $$ LANGUAGE plpgsql; \
         CREATE TRIGGER {prefix}_agent_revision_insert AFTER INSERT ON {prefix}_agent \
            FOR EACH ROW EXECUTE FUNCTION {prefix}_capture_agent_revision(); \
         CREATE TRIGGER {prefix}_agent_revision_update AFTER UPDATE ON {prefix}_agent \
            FOR EACH ROW WHEN (OLD.generation IS DISTINCT FROM NEW.generation) \
            EXECUTE FUNCTION {prefix}_capture_agent_revision()",
        "CREATE TABLE {prefix}_agent_revision (\
            scope_id TEXT NOT NULL, id TEXT NOT NULL, generation BIGINT NOT NULL, \
            data TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, \
            PRIMARY KEY (scope_id, id, generation)); \
         INSERT INTO {prefix}_agent_revision (scope_id, id, generation, data) \
            SELECT scope_id, id, generation, data FROM {prefix}_agent; \
         CREATE TRIGGER {prefix}_agent_revision_insert AFTER INSERT ON {prefix}_agent BEGIN \
            INSERT INTO {prefix}_agent_revision (scope_id, id, generation, data) \
              VALUES (NEW.scope_id, NEW.id, NEW.generation, NEW.data); END; \
         CREATE TRIGGER {prefix}_agent_revision_update AFTER UPDATE ON {prefix}_agent \
            WHEN OLD.generation <> NEW.generation BEGIN \
            INSERT INTO {prefix}_agent_revision (scope_id, id, generation, data) \
              VALUES (NEW.scope_id, NEW.id, NEW.generation, NEW.data); END",
    )?);
    migrations.push(Migration::per_dialect(
        10,
        "agent configs and publications: identity is scoped, not globally first-writer-owned",
        "ALTER TABLE {prefix}_agent DROP CONSTRAINT {prefix}_agent_pkey; \
         ALTER TABLE {prefix}_agent ADD PRIMARY KEY (scope_id, id); \
         ALTER TABLE {prefix}_publication DROP CONSTRAINT {prefix}_publication_pkey; \
         ALTER TABLE {prefix}_publication ADD PRIMARY KEY (scope_id, fingerprint)",
        "DROP TRIGGER {prefix}_agent_revision_insert; \
         DROP TRIGGER {prefix}_agent_revision_update; \
         ALTER TABLE {prefix}_agent RENAME TO {prefix}_agent_unscoped; \
         CREATE TABLE {prefix}_agent (\
            id TEXT NOT NULL, data TEXT NOT NULL, \
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, \
            scope_id TEXT NOT NULL DEFAULT 'default', \
            generation BIGINT NOT NULL DEFAULT 1, \
            PRIMARY KEY (scope_id, id)); \
         INSERT INTO {prefix}_agent (id, data, created_at, scope_id, generation) \
            SELECT id, data, created_at, scope_id, generation \
            FROM {prefix}_agent_unscoped ORDER BY rowid; \
         DROP TABLE {prefix}_agent_unscoped; \
         CREATE TRIGGER {prefix}_agent_revision_insert AFTER INSERT ON {prefix}_agent BEGIN \
            INSERT INTO {prefix}_agent_revision (scope_id, id, generation, data) \
              VALUES (NEW.scope_id, NEW.id, NEW.generation, NEW.data); END; \
         CREATE TRIGGER {prefix}_agent_revision_update AFTER UPDATE ON {prefix}_agent \
            WHEN OLD.generation <> NEW.generation BEGIN \
            INSERT INTO {prefix}_agent_revision (scope_id, id, generation, data) \
              VALUES (NEW.scope_id, NEW.id, NEW.generation, NEW.data); END; \
         ALTER TABLE {prefix}_publication RENAME TO {prefix}_publication_unscoped; \
         CREATE TABLE {prefix}_publication (\
            fingerprint TEXT NOT NULL, agent_id TEXT NOT NULL, state TEXT NOT NULL, \
            record TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, \
            scope_id TEXT NOT NULL DEFAULT 'default', \
            PRIMARY KEY (scope_id, fingerprint)); \
         INSERT INTO {prefix}_publication \
            (fingerprint, agent_id, state, record, created_at, scope_id) \
            SELECT fingerprint, agent_id, state, record, created_at, scope_id \
            FROM {prefix}_publication_unscoped ORDER BY rowid; \
         DROP TABLE {prefix}_publication_unscoped; \
         CREATE INDEX {prefix}_publication_created_at_idx \
            ON {prefix}_publication (created_at)",
    )?);
    MigrationBundle::new(BUNDLE_ID, migrations)
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use awaken_scoped_migration::{Dialect, plan};

    use super::config_bundle;

    #[test]
    fn deployed_sqlite_v9_ledger_upgrades_without_historical_checksum_drift() {
        let applied = BTreeMap::from([
            (
                1,
                "3134e209014343fdb07c7e57bedbdd42a27fab4017e9b2c6a7a69f3d68dcf588".into(),
            ),
            (
                2,
                "76f0182f64e73c863acb737c25f3507d0e81ec01d5c6967331dc3c9ef3a9aab6".into(),
            ),
            (
                3,
                "fe8e6854ed3e22e3f8940cf64f2c1064b4a856bba57e6a38e2972c92f8340851".into(),
            ),
            (
                4,
                "5f7faf0e50e577be972afdf0f32dc1140f6cf00edf2c7db8b5808fd27179d22f".into(),
            ),
            (
                5,
                "3811e84d319e0dd8d4f0f16d75fb2b7a73b5d76acb759f05518468b76682acd5".into(),
            ),
            (
                6,
                "00dec487869e300b97c26a44898b0fb7af0da0d438eff69afe7c177b7f8d7a0d".into(),
            ),
            (
                7,
                "ca632a2fcd446c6f0fde5f581f7d4be2be0ed4bea94e9d80646ed712200d97c9".into(),
            ),
            (
                8,
                "c5729c8a7e39fc422fed94bdc1892ad9b1e5e652595e89e2e0cc9903ea2427c8".into(),
            ),
            (
                9,
                "9957a1bf1c53dfa318e927883f34f4200fe00f5db1853a272d63389022a96814".into(),
            ),
        ]);

        let bundle = config_bundle().unwrap();
        let pending = plan(&bundle, &applied, Dialect::Sqlite).unwrap();
        assert_eq!(
            pending
                .into_iter()
                .map(awaken_scoped_migration::Migration::version)
                .collect::<Vec<_>>(),
            vec![10]
        );
    }
}
