apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../bases/postgres
  - ../bases/topology-direct
patches:
  - path: brain-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: brain
