//! Emit the Rust-derived Managed Agents compatibility schemas.

use serde_json::{Value, json};

fn main() {
    let capabilities = awaken_protocol_managed::ManagedCapability::ALL.map(|capability| {
        json!({
            "id": capability.id(),
            "beta": capability.beta(),
        })
    });
    let root = json!({
        "$comment": "GENERATED by awaken-protocol-managed export_schemas; do not edit.",
        "schema_version": 1,
        "protocol": {
            "anthropic_api_version": awaken_protocol_managed::ANTHROPIC_API_VERSION,
            "capabilities": capabilities,
        },
        "schemas": Value::Object(awaken_protocol_managed::schema::contract_schemas()),
    });
    println!(
        "{}",
        serde_json::to_string_pretty(&root).expect("schema bundle serializes")
    );
}
