//! Emit the Rust-derived Managed Agents compatibility schemas.

use serde_json::{Value, json};

fn main() {
    let root = json!({
        "$comment": "GENERATED by awaken-protocol-managed export_schemas; do not edit.",
        "anthropic_sdk": "0.120.0",
        "schemas": Value::Object(awaken_protocol_managed::schema::contract_schemas()),
    });
    println!(
        "{}",
        serde_json::to_string_pretty(&root).expect("schema bundle serializes")
    );
}
