// GENERATED by scripts/contract/generate-contracts.sh — do not edit.
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ResourceAccess".
 */
export type ResourceAccess = "read_only" | "read_write";
/**
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "InputResourceId".
 */
export type InputResourceId =
  | {
      id: string;
      kind: "file";
      [k: string]: unknown;
    }
  | {
      id: string;
      kind: "memory_store";
      [k: string]: unknown;
    }
  | {
      id: string;
      kind: "repository";
      [k: string]: unknown;
    };
/**
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CloudLoginState".
 */
export type CloudLoginState = "sign_in_required" | "authorizing" | "authenticated" | "failed";
/**
 * A credential pool identifier.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CredentialPoolId".
 */
export type CredentialPoolId = string;
/**
 * Stable, secret-free identity of a credential source.
 *
 * The identifier crosses Control-to-Coordinator application ports, so its
 * canonical owner is the credential contract rather than the Vault adapter.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CredentialSourceId".
 */
export type CredentialSourceId = string;
/**
 * How a pool picks among its eligible members — the *intent* behind selection,
 * consumed by the runtime selector (an availability-aware picker, per ADR-0043).
 * The pool's [`selection_order`](CredentialPool::selection_order) always yields the
 * eligible members in ordinal order; this policy decides which of them the picker
 * commits to.
 *
 * Names align with awaken-next's `SelectionPolicy`. `#[non_exhaustive]` so adding a
 * policy is not a breaking change.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "SelectionPolicy".
 */
export type SelectionPolicy = "first_healthy" | "rotate_spread" | "sticky_resume";
/**
 * Exact upstream audience authorized for a credential purpose.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CredentialAudienceRef".
 */
export type CredentialAudienceRef = string;
/**
 * Secret-free description of the material document sealed by the Vault.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CredentialMaterialDescriptor".
 */
export type CredentialMaterialDescriptor =
  | {
      kind: "secret";
      type_id: CredentialMaterialTypeId;
    }
  | {
      fields: string[];
      kind: "structured";
      type_id: CredentialMaterialTypeId;
    };
/**
 * Namespaced, versioned material shape identifier.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CredentialMaterialTypeId".
 */
export type CredentialMaterialTypeId = string;
/**
 * Provider-owned permission/scope label exposed only as secret-free metadata.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CredentialPermissionRef".
 */
export type CredentialPermissionRef = string;
/**
 * Provider namespace recorded as secret-free credential metadata. This names
 * the upstream provider (`github`), never a product resource kind such as
 * `github_repository`.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CredentialProviderRef".
 */
export type CredentialProviderRef = string;
/**
 * Opaque provider subject such as one account or installation. This is
 * metadata for binding/probing, not an IAM principal.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CredentialSubjectRef".
 */
export type CredentialSubjectRef = string;
/**
 * Why a target is allowed to consume the credential. Purpose is orthogonal to
 * provider identity and material shape.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CredentialPurpose".
 */
export type CredentialPurpose =
  | {
      type: "provider_adapter";
    }
  | {
      type: "repository_transport";
    }
  | {
      type: "mcp_authorization";
    }
  | {
      type: "http_effect";
    }
  | {
      type: "signature_verification";
    }
  | {
      type: "extension";
    };
/**
 * How the resolved endpoint consumes injected material.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CredentialUsage".
 */
export type CredentialUsage =
  | {
      type: "provider_adapter";
      [k: string]: unknown;
    }
  | {
      name: string;
      scheme?: string | null;
      type: "http_header";
      [k: string]: unknown;
    }
  | {
      type: "http_basic_auth";
      [k: string]: unknown;
    }
  | {
      consumer_id: string;
      material_type: string;
      public_config?: unknown;
      type: "extension";
      [k: string]: unknown;
    }
  | {
      name: string;
      type: "query_parameter";
      [k: string]: unknown;
    }
  | {
      fields: {
        [k: string]: HttpEffectPlacement[];
      };
      type: "http_effect";
      [k: string]: unknown;
    }
  | {
      fields: {
        [k: string]: SignatureVerificationAlgorithm[];
      };
      type: "signature_verification";
      [k: string]: unknown;
    }
  | {
      type: "client_certificate";
      [k: string]: unknown;
    }
  | {
      name: string;
      type: "environment_variable";
      [k: string]: unknown;
    }
  | {
      path: string;
      type: "file";
      [k: string]: unknown;
    };
/**
 * One exact destination at which a hosted HTTP effect may render a material
 * field. JSON pointers are rooted at the effect's `json` or `body` value.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "HttpEffectPlacement".
 */
export type HttpEffectPlacement =
  | {
      name: string;
      type: "header";
    }
  | {
      name: string;
      type: "query";
    }
  | {
      pointer: string;
      type: "json_pointer";
    };
/**
 * Closed provider-neutral algorithms implemented by the host verification
 * boundary. Provider-specific message construction remains in the caller.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "SignatureVerificationAlgorithm".
 */
export type SignatureVerificationAlgorithm = "hmac_sha256" | "sha256_parts" | "constant_time";
/**
 * Where a secret physically lives (the materialization axis).
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CredentialKind".
 */
export type CredentialKind = "vault" | "env" | "oauth" | "worker_local";
/**
 * Lifecycle of a source.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CredentialStatus".
 */
export type CredentialStatus = "active" | "disabled" | "archived";
/**
 * Server-owned OAuth token helper. The API carries this allowlisted id, never
 * an operator-supplied command line; the credential bounded context owns how
 * it becomes a token source for model, MCP, and A2A consumers alike.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "OAuthHelper".
 */
export type OAuthHelper = "gcloud";
/**
 * The result of a live credential probe (secret-free), aligned with the Managed
 * wire's `valid` / `invalid` / `unknown` statuses.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ProbeStatus".
 */
export type ProbeStatus = "valid" | "invalid" | "unknown";
/**
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ExecutableModelReadiness".
 */
export type ExecutableModelReadiness =
  "ready" | "offering_unavailable" | "credential_unavailable" | "runtime_unavailable" | "dialect_unavailable";
/**
 * How one exact published Provider candidate obtains access. This is a
 * provider-neutral execution fact: it is neither catalog provenance nor a
 * commercial funding decision.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ProviderAccessKind".
 */
export type ProviderAccessKind = "direct" | "brokered";
/**
 * The "which credential" axis (oversight-next / awaken-management-contract).
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CredentialBinding".
 */
export type CredentialBinding =
  | {
      type: "none";
      [k: string]: unknown;
    }
  | {
      type: "brokered";
      [k: string]: unknown;
    }
  | {
      credential_source_id: CredentialSourceId;
      type: "exact";
      [k: string]: unknown;
    }
  | {
      credential_pool_id: CredentialPoolId;
      type: "one_of_credential_pool";
      [k: string]: unknown;
    };
/**
 * Authority behind one published model-attribute value.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ModelAttributeSource".
 */
export type ModelAttributeSource = "manual" | "provider_api" | "curated" | "brokered";
/**
 * The wire/model-API dialect a surface speaks. Replaces oversight's `WireFormat`;
 * the credential/model bindings are resolved against this dialect (ADR-0043).
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ApiDialect".
 */
export type ApiDialect = "anthropic_messages" | "open_ai_chat" | "open_ai_responses" | "gemini" | "vertex_gemini";
/**
 * Authority that published an [`Offering`].
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "OfferingSource".
 */
export type OfferingSource = "manual" | "provider_api" | "brokered";
/**
 * Admission status for new publications using an offering.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "OfferingStatus".
 */
export type OfferingStatus = "active" | "unavailable";
/**
 * Stable id of a [`ProtocolEndpoint`].
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ProtocolEndpointId".
 */
export type ProtocolEndpointId = string;
/**
 * Stable id of a [`Provider`] (vendor namespace).
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ProviderId".
 */
export type ProviderId = string;
/**
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ProviderConnectionStatus".
 */
export type ProviderConnectionStatus =
  "not_configured" | "connected" | "ready" | "stale" | "needs_attention" | "unavailable";
/**
 * Authentication input a provider connection can request. This describes the
 * authoring UI only; credential material remains owned by the vault.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ProviderAuthMethod".
 */
export type ProviderAuthMethod = "api_key" | "oauth";
/**
 * Input widget rendered from a provider descriptor. Descriptors are static
 * adapter capabilities, not user configuration and not another model catalog.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ProviderFieldKind".
 */
export type ProviderFieldKind = "secret" | "text" | "url";
/**
 * The availability of one credential source at a point in time.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "AvailabilityState".
 */
export type AvailabilityState =
  | {
      state: "available";
      [k: string]: unknown;
    }
  | {
      retry_at_ms: number;
      state: "cooled_down";
      [k: string]: unknown;
    }
  | {
      state: "exhausted";
      [k: string]: unknown;
    };
/**
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ModelSelection".
 */
export type ModelSelection =
  | {
      mode: "auto";
    }
  | {
      mode: "profile";
      profile_id: string;
    }
  | {
      backend_ref: string;
      configuration?: AcpSessionConfiguration;
      mode: "target";
      target: ModelTarget;
    }
  | {
      backend_ref: string;
      configuration?: AcpSessionConfiguration;
      mode: "backend_default";
    }
  | {
      backend_ref: string;
      configuration?: AcpSessionConfiguration;
      mode: "backend_exact";
      model_ref: string;
    }
  | {
      backend_ref: string;
      mode: "pinned";
      model_ref: string;
      provider_identity_ref: string;
    };
/**
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "APIDialect".
 */
export type APIDialect = ApiDialect;
/**
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "APIError".
 */
export type APIError = ApiError;
/**
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "PrimaryElement".
 */
export type PrimaryElement = ProfileCandidate;

/**
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "AgentEnvironmentBinding".
 */
export interface AgentEnvironmentBinding {
  environment_id: string;
  revision: number;
}
/**
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "InputBinding".
 */
export interface InputBinding {
  access: ResourceAccess;
  binding_id: string;
  instructions?: string | null;
  mount_path: string;
  target: InputResourceId;
  [k: string]: unknown;
}
/**
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "IdentityCapabilityView".
 */
export interface IdentityCapabilityView {
  authenticated: boolean;
  cloud_login_enabled: boolean;
  mode: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ModelSupplyCapabilityView".
 */
export interface ModelSupplyCapabilityView {
  byok_enabled: boolean;
  cloud_models_enabled: boolean;
  local_catalog_enabled: boolean;
  profile_authoring_enabled: boolean;
  [k: string]: unknown;
}
/**
 * Product surfaces actually mounted by the same-origin process composition.
 * This is presentation discovery only; mounted routes retain their own PEP.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ProductSurfaceCapabilityView".
 */
export interface ProductSurfaceCapabilityView {
  access_management: boolean;
  managed_runtime: boolean;
  [k: string]: unknown;
}
/**
 * One source's membership in a pool. `ordinal` is the default selection order
 * (ascending); a disabled member is skipped. `selection_weight` is reserved for a
 * future weighted policy and does not affect the default ordinal order.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CredentialPoolMember".
 */
export interface CredentialPoolMember {
  credential_source_id: CredentialSourceId;
  enabled: boolean;
  ordinal: number;
  selection_weight?: number;
  [k: string]: unknown;
}
/**
 * One normalized, secret-free description stored on the canonical source row.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CredentialDescriptor".
 */
export interface CredentialDescriptor {
  expires_at_unix_ms?: number | null;
  material: CredentialMaterialDescriptor;
  permissions?: CredentialPermissionRef[];
  provider: CredentialProviderRef;
  subject?: CredentialSubjectRef | null;
  /**
   * Exact authorized target/usage contracts. Separate sets are deliberately
   * forbidden because their Cartesian product would invent undeclared uses.
   */
  targets: CredentialTargetContract[];
}
/**
 * One source-declared authorization contract. The target identity and its
 * allowed material usage are indivisible here, while executable access carries
 * that target identity plus its existing single `usage` field.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CredentialTargetContract".
 */
export interface CredentialTargetContract {
  target: CredentialTarget;
  usage: CredentialUsage;
}
/**
 * Exact purpose/audience identity frozen into executable access. Usage remains
 * the existing independent field on `CredentialAccess`, so executable payloads
 * cannot serialize two copies of the same usage truth.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CredentialTarget".
 */
export interface CredentialTarget {
  audience: CredentialAudienceRef;
  purpose: CredentialPurpose;
}
/**
 * A stable reference to one credential source revision.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CredentialRef".
 */
export interface CredentialRef {
  id: string;
  revision: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CredentialMaterialInput".
 */
export interface CredentialMaterialInput {
  /**
   * Opaque named secret fields; the matching consumer owns validation.
   */
  fields: {
    [k: string]: string;
  };
  /**
   * Namespaced, versioned type owned by the installed consumer extension.
   */
  type_id: string;
  [k: string]: unknown;
}
/**
 * Stable authoring identity used to select one catalog Offering.
 *
 * `endpoint_name` is the human qualifier used by public model ids. Resolution
 * maps it to a concrete endpoint after dialect negotiation. Exact config and
 * profile authoring may instead use `protocol_endpoint_id`; admission rejects
 * a target containing both.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ModelTarget".
 */
export interface ModelTarget {
  /**
   * Public API-dialect qualifier (for example `anthropic_messages` or
   * `open_ai_responses`). It narrows a provider's protocol surfaces without
   * exposing the catalog's internal endpoint identity.
   */
  api_dialect?: string | null;
  endpoint_name?: string | null;
  model_id: string;
  protocol_endpoint_id?: string | null;
  provider_id?: string | null;
  [k: string]: unknown;
}
/**
 * One explicit step in a profile's failover chain. Binding credentials per
 * target allows a BYOK primary and Cloud fallback (or the reverse) without ever
 * guessing which identity may authenticate which provider.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ProfileCandidate".
 */
export interface ProfileCandidate {
  credential_binding: CredentialBinding;
  target: ModelTarget;
  [k: string]: unknown;
}
/**
 * Explainability metadata for one field in [`ModelAttributes`].
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ModelAttributeProvenance".
 */
export interface ModelAttributeProvenance {
  observed_at_unix_ms: number;
  source: ModelAttributeSource;
  [k: string]: unknown;
}
/**
 * Adapter-native ACP Session intent attached to an Agent model selection.
 *
 * Values remain strings because the selected ACP runtime's negotiated
 * capability descriptor is the authority that validates supported modes and
 * option values at publication time.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "AcpSessionConfiguration".
 */
export interface AcpSessionConfiguration {
  mode?: string | null;
  options?: {
    [k: string]: string;
  };
  /**
   * Portable path relative to the Session workspace. The host maps it to the
   * environment's interior root before sending ACP `session/new.cwd`.
   */
  working_directory?: string | null;
}
/**
 * The published intrinsic attributes of a catalog model, keyed by `model_id`. This is
 * the control plane's OWN projection of what a console publishes — deliberately not the
 * agent-domain `ModelSpec` (a runtime type the control plane must not depend on, per the
 * dependency-direction ban); it carries only what the catalog's consumers read. Extended
 * as the console publishes more attributes.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ModelAttributes".
 */
export interface ModelAttributes {
  /**
   * Max context window in tokens — the single budget both the ACP CLIs' auto-compact
   * window and the native compaction ext derive from. Absent → the consumer falls back.
   */
  context_window?: number | null;
  /**
   * Max output tokens the model emits, when published.
   */
  max_output_tokens?: number | null;
  /**
   * Field-level origin. Values stay flat and convenient for runtime consumers;
   * management surfaces use this map to explain whether each fact was authored,
   * observed from a provider API, or supplied by Awaken's curated registry.
   */
  provenance?: {
    [k: string]: ModelAttributeProvenance;
  };
  [k: string]: unknown;
}
/**
 * A model reachable on a protocol surface. `model_id` references the catalog's
 * [`ModelAttributes`] (the intrinsic model attributes the control plane publishes).
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "Offering".
 */
export interface Offering {
  dialect: ApiDialect;
  /**
   * Unix timestamp (milliseconds) of the most recent complete provider listing
   * that contained this route. Manual offerings never carry this observation.
   * When a later complete listing omits the model, the timestamp is retained so
   * operators can distinguish "last seen then" from "never observed".
   */
  last_seen_at_unix_ms?: number | null;
  /**
   * The protocol-agnostic catalog model id (e.g. `claude-opus-4-8`).
   */
  model_id: string;
  protocol_endpoint_id: ProtocolEndpointId;
  provider_id: ProviderId;
  /**
   * Who owns the catalog fact. Manually authored rows are never demoted by a
   * provider refresh; provider-discovered rows follow the provider's latest
   * complete listing.
   */
  source?: OfferingSource;
  /**
   * Whether this route may be selected for a new publication. Provider sync is
   * non-destructive: a missing discovered model becomes unavailable instead of
   * being deleted, so existing immutable publications remain explainable.
   */
  status?: OfferingStatus;
  /**
   * Provider-canonical model name sent upstream when it differs from `model_id`.
   */
  upstream_model?: string | null;
  [k: string]: unknown;
}
/**
 * A concrete protocol surface of a provider: which wire + which URL. Distinct
 * flavors of one provider typically have distinct `base_url`s.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ProtocolEndpoint".
 */
export interface ProtocolEndpoint {
  /**
   * `http(s)` base URL override (proxy / self-hosted / compat endpoint).
   */
  base_url?: string | null;
  dialect: ApiDialect;
  display_name: string;
  id: ProtocolEndpointId;
  provider_id: ProviderId;
  /**
   * Request timeout in seconds.
   */
  timeout_secs: number;
  version: number;
  [k: string]: unknown;
}
/**
 * A vendor namespace (`anthropic`, `openai`, …).
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "Provider".
 */
export interface Provider {
  display_name: string;
  id: ProviderId;
  /**
   * URL-safe vendor slug, unique in the catalog.
   */
  slug: string;
  /**
   * Append-only version bumped on change.
   */
  version: number;
  [k: string]: unknown;
}
/**
 * Durable outcome of reconciling one complete provider model listing.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CatalogSyncResult".
 */
export interface CatalogSyncResult {
  activated: number;
  discovered: number;
  marked_unavailable: number;
  /**
   * Observation time shared by every row in this successful atomic refresh.
   */
  observed_at_unix_ms: number;
  [k: string]: unknown;
}
/**
 * Secret-free credential projection. Internal token-source argv and Vault refs
 * never cross the admin boundary; consumers bind this stable source id.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CredentialSourceView".
 */
export interface CredentialSourceView {
  descriptor?: CredentialDescriptor | null;
  env_key?: string | null;
  id: CredentialSourceId;
  kind: CredentialKind;
  oauth_helper?: OAuthHelper | null;
  protocol_endpoint_id?: string | null;
  provider_id?: string | null;
  replacement_of?: CredentialRef | null;
  status: CredentialStatus;
  version: number;
  workspace_id: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "DefaultProtocolEndpoint".
 */
export interface DefaultProtocolEndpoint {
  base_url: string;
  dialect: ApiDialect;
  /**
   * Optional provider-owned model-directory base when discovery is exposed
   * separately from the inference protocol surface.
   */
  model_discovery_base_url?: string | null;
  /**
   * Provider-verified model ids for this protocol surface. An empty list
   * means every model returned by the provider directory is compatible.
   */
  supported_model_ids?: string[];
  [k: string]: unknown;
}
/**
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ProviderConfigurationField".
 */
export interface ProviderConfigurationField {
  advanced: boolean;
  key: string;
  kind: ProviderFieldKind;
  label: string;
  placeholder?: string | null;
  required: boolean;
  [k: string]: unknown;
}
/**
 * The **secret-free** result of a resolve (ADR-0043): the execution triple + the
 * adapter/endpoint it binds to, and whether a credential resolved — never the
 * secret itself. This is what an operator's "test binding" call sees.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ResolvedInferenceView".
 */
export interface ResolvedInferenceView {
  adapter_kind: string;
  base_url?: string | null;
  /**
   * Whether a credential was materialized (never the value).
   */
  credential_present: boolean;
  model_id: string;
  protocol_endpoint_id: string;
  provider_id: string;
  [k: string]: unknown;
}
/**
 * An Agent's authored default Environment and Resource inputs. Workspace is
 * the repository aggregate key; this value contains only Agent-local intent.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "AgentInputConfig".
 */
export interface AgentInputConfig {
  agent_id: string;
  environment?: AgentEnvironmentBinding | null;
  inputs: InputBinding[];
  revision: number;
}
/**
 * RFC 9457 Problem Details with stable application extension members (`code`, `request_id`, `details`, `errors`).
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ApiError".
 */
export interface ApiError {
  /**
   * Stable application error code; clients may branch on this.
   */
  code: string;
  /**
   * Request-specific human-readable explanation.
   */
  detail?: string;
  /**
   * Type-specific structured metadata.
   */
  details?: unknown;
  /**
   * Field/query/header violations for validation-style problems.
   */
  errors?: {
    code: string;
    field: string;
    message?: string;
    [k: string]: unknown;
  }[];
  instance?: string;
  /**
   * Correlation id echoed from the `x-request-id` header.
   */
  request_id: string;
  status: number;
  /**
   * Stable human-readable summary for this problem type.
   */
  title: string;
  /**
   * URI reference identifying the problem type.
   */
  type: string;
  [k: string]: unknown;
}
/**
 * Retire one exact credential revision. The expected version is mandatory so
 * an operator cannot erase material that was rotated after its read.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ArchiveCredentialRequest".
 */
export interface ArchiveCredentialRequest {
  expected_version: number;
  [k: string]: unknown;
}
/**
 * Secret-free state of the one product-coordinated Cloud login operation.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CloudLoginStatusView".
 */
export interface CloudLoginStatusView {
  authorize_url?: string | null;
  error_code?: string | null;
  state: CloudLoginState;
  [k: string]: unknown;
}
/**
 * Stable frontend/SDK feature discovery; callers never infer deployment
 * posture from a failed Cloud request.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ConfigCapabilitiesView".
 */
export interface ConfigCapabilitiesView {
  identity: IdentityCapabilityView;
  models: ModelSupplyCapabilityView;
  surfaces: ProductSurfaceCapabilityView;
  [k: string]: unknown;
}
/**
 * A cooldown signal an operator (or an external rate-limit integration) records
 * against a credential source. `kind` maps to a failure
 * [`Disposition`](awaken_runtime_contract::resilience::Disposition): `quota` cools
 * until `retry_after_secs` (or a default window); `exhausted` cools until cleared;
 * `available` / `clear` lifts any cooldown; `transient` / `permanent` are no-ops on
 * availability (they are retry/next-binding decisions, not identity cooldowns).
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CooldownRequest".
 */
export interface CooldownRequest {
  kind: string;
  retry_after_secs?: number | null;
  [k: string]: unknown;
}
/**
 * A pool of interchangeable credential sources for one provider principal
 * (oversight-next account grouping). The resolver picks one eligible member per
 * run; members are tried in policy order so a disabled/exhausted member fails
 * over to the next rather than failing the run (fail-closed only when none work).
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CredentialPool".
 */
export interface CredentialPool {
  id: CredentialPoolId;
  members: CredentialPoolMember[];
  /**
   * How the selector picks among eligible members. `#[serde(default)]` keeps
   * existing pool rows (persisted as JSON) loadable as [`FirstHealthy`], the
   * historical behavior.
   *
   * [`FirstHealthy`]: SelectionPolicy::FirstHealthy
   */
  policy?: SelectionPolicy & string;
  workspace_id: string;
  [k: string]: unknown;
}
/**
 * The secret-free result of a live credential probe.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "CredentialValidation".
 */
export interface CredentialValidation {
  adapter_kind: string;
  /**
   * Current durable revision for an exact hosted reference validation.
   * Model live-probe responses omit it.
   */
  credential_version?: number | null;
  status: ProbeStatus;
  [k: string]: unknown;
}
/**
 * The credential-entry wire body. `secret` is write-only: it is sealed into the
 * SecretStore and never appears on any response. `RedactedString` is
 * intentionally not `Deserialize`, so the raw secret crosses the wire once.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "EnterCredentialRequest".
 */
export interface EnterCredentialRequest {
  /**
   * Canonical secret-free provider, material, and exact target/usage facts.
   * Legacy clients may omit it; described clients receive it on exact reads
   * and must omit the mutually exclusive legacy `provider_id`.
   */
  descriptor?: CredentialDescriptor | null;
  env_key?: string | null;
  /**
   * Stable hosted-governance operation identity. When present, the canonical
   * provider comes from `descriptor` or the legacy `provider_id`; described
   * writes reject `provider_id` so that tuple has one provider truth.
   */
  idempotency_key?: string | null;
  kind: CredentialKind;
  /**
   * Structured material sealed as one versioned Vault document. Mutually
   * exclusive with the legacy `secret` field.
   */
  material?: CredentialMaterialInput | null;
  /**
   * A server-owned OAuth refresh helper. This is an allowlisted identifier,
   * never an operator-supplied command line.
   */
  oauth_helper?: OAuthHelper | null;
  provider_id?: string | null;
  /**
   * Exact active predecessor fenced while this request publishes a distinct
   * deterministic source. The predecessor is not mutated or retired.
   */
  replacement_of?: CredentialRef | null;
  /**
   * The secret to seal — required for `vault`. Environment-backed credentials
   * are not accepted; environment discovery is exposed only as proposals.
   */
  secret?: string | null;
  workspace_id: string;
  [k: string]: unknown;
}
/**
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ExecutableModelOption".
 */
export interface ExecutableModelOption {
  access_kind: ProviderAccessKind;
  backend_ref: string;
  dialect: string;
  endpoint_id: string;
  model_id: string;
  provider_id: string;
  readiness: ExecutableModelReadiness;
  [k: string]: unknown;
}
/**
 * An authored "how to run this model" unit: it names an exact primary and
 * ordered fallback candidates, each with a vault-backed (never inline)
 * credential binding, plus endpoints the operator has toggled off. The resolver
 * reads it — it is never flowed into the runtime.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "InferenceProfile".
 */
export interface InferenceProfile {
  disabled_endpoint_ids?: string[];
  /**
   * Explicit alternates, tried in authored order. The resolver never appends an
   * implicit Cloud, BYOK, or local fallback.
   */
  fallbacks?: ProfileCandidate[];
  /**
   * Exact preferred offering. Provider and endpoint qualifiers prevent a model
   * id shared by BYOK and Cloud sources from becoming ambiguous at runtime.
   */
  primary: ProfileCandidate;
  /**
   * Owning workspace, stamped by the trusted configuration edge. An empty
   * value represents an unstamped domain value and is never treated as owned.
   */
  workspace_id?: string;
}
/**
 * Which members of a pool are selectable right now — `selection_order` with cooled
 * members dropped (`eligible_order`). The ops view of the mid-run rotation.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "PoolEligibleView".
 */
export interface PoolEligibleView {
  cooled: string[];
  eligible: string[];
  [k: string]: unknown;
}
/**
 * The catalog aggregate: providers, their endpoints, and the offerings across
 * them. The in-memory projection the resolver queries.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ProviderCatalog".
 */
export interface ProviderCatalog {
  endpoints: {
    [k: string]: ProtocolEndpoint;
  };
  /**
   * The published attributes of the models the offerings reference, keyed by
   * `model_id`. Absent for a model whose attributes aren't published (the consumer
   * then falls back — e.g. compaction stays message-count based).
   */
  model_attributes?: {
    [k: string]: ModelAttributes;
  };
  offerings: Offering[];
  providers: {
    [k: string]: Provider;
  };
  [k: string]: unknown;
}
/**
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ProviderConnectionSummary".
 */
export interface ProviderConnectionSummary {
  active_credentials: number;
  active_models: number;
  display_name: string;
  endpoint_ids: string[];
  last_seen_at_unix_ms?: number | null;
  provider_id: string;
  status: ProviderConnectionStatus;
  unavailable_models: number;
  [k: string]: unknown;
}
/**
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ProviderConnectionView".
 */
export interface ProviderConnectionView {
  credential: CredentialSourceView;
  endpoint: ProtocolEndpoint;
  provider: Provider;
  sync: CatalogSyncResult;
  [k: string]: unknown;
}
/**
 * One supported provider driver's authoring capabilities. The list returned by
 * [`provider_driver_descriptors`] is the single source used by API clients to
 * render provider cards and forms.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ProviderDriverDescriptor".
 */
export interface ProviderDriverDescriptor {
  auth_methods: ProviderAuthMethod[];
  configuration_fields: ProviderConfigurationField[];
  default_endpoints: DefaultProtocolEndpoint[];
  display_name: string;
  documentation_url?: string | null;
  provider_kind: string;
  supported_dialects: ApiDialect[];
  supports_model_discovery: boolean;
  [k: string]: unknown;
}
/**
 * Secret-free authoring input. Provenance is intentionally absent: external
 * callers cannot claim that a manual value came from a provider or curated source.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "PutModelAttributesRequest".
 */
export interface PutModelAttributesRequest {
  context_window?: number | null;
  max_output_tokens?: number | null;
}
/**
 * Resolve an authored profile within a workspace's credential scope.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ResolveProfileRequest".
 */
export interface ResolveProfileRequest {
  workspace_id: string;
  [k: string]: unknown;
}
/**
 * A dry-run resolve request. An unqualified target is valid when the model id
 * identifies exactly one active offering; callers always use the same target shape.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ResolveRequest".
 */
export interface ResolveRequest {
  binding: CredentialBinding;
  target: ModelTarget;
  workspace_id: string;
}
/**
 * The ordered candidate list a profile resolves to (E3-2): one secret-free view per
 * model in the profile's axis, in failover order.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ResolvedCandidatesView".
 */
export interface ResolvedCandidatesView {
  candidates: ResolvedInferenceView[];
  [k: string]: unknown;
}
/**
 * Rotate the primary material of one exact active Vault credential revision.
 * Scalar or typed material is write-only and the response remains secret-free.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "RotateCredentialRequest".
 */
export interface RotateCredentialRequest {
  /**
   * Replacement metadata published by the same expected-version CAS.
   */
  descriptor?: CredentialDescriptor | null;
  expected_version: number;
  material?: CredentialMaterialInput | null;
  secret?: string | null;
  [k: string]: unknown;
}
/**
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "SaveProviderConnectionRequest".
 */
export interface SaveProviderConnectionRequest {
  base_url?: string | null;
  configuration?: {
    [k: string]: string;
  };
  /**
   * Optional human label embedded into the generated credential source id.
   * It is non-secret and does not replace the stable idempotency fingerprint.
   */
  credential_name?: string | null;
  /**
   * Reuse one active Workspace credential instead of creating a duplicate.
   */
  credential_source_id?: CredentialSourceId | null;
  dialect: ApiDialect;
  display_name: string;
  /**
   * Optional stable qualifier for a second endpoint using the same dialect.
   */
  endpoint_name?: string | null;
  idempotency_key: string;
  /**
   * Server-owned OAuth helper used to mint a short-lived token for both the
   * pre-save discovery and the persisted credential source.
   */
  oauth_helper?: OAuthHelper | null;
  provider_id: string;
  /**
   * Write-only API key. Exactly one of `secret`, `oauth_helper`, or
   * `credential_source_id` must be supplied; the connection command is the
   * one authoring path for every supported credential source.
   */
  secret?: string | null;
  timeout_secs?: number;
  workspace_id: string;
}
/**
 * Live-validate a credential against a model's resolved provider endpoint.
 *
 * This interface was referenced by the generated JSON Schema
 * via the `definition` "ValidateCredentialRequest".
 */
export interface ValidateCredentialRequest {
  model_id?: string | null;
  /**
   * Generic hosted-governance validation mode. The durable source id is the
   * path identity, so this field is mutually exclusive with `model_id`.
   */
  provider_ref?: string | null;
  workspace_id: string;
  [k: string]: unknown;
}
