// GENERATED by scripts/contract/generate-contracts.sh — do not edit.
/**
 * A management-plane MCP server identifier.
 *
 * Stable id of a [`CredentialSource`].
 *
 * A credential pool identifier.
 *
 * Opaque handle into a [`SecretStore`]. Never the secret itself.
 *
 * Stable id of a [`ProtocolEndpoint`].
 *
 * Stable id of a [`Provider`] (vendor namespace).
 */
type CredentialPoolID = string;

/**
 * A management-plane MCP server identifier.
 *
 * Stable id of a [`CredentialSource`].
 *
 * A credential pool identifier.
 *
 * Opaque handle into a [`SecretStore`]. Never the secret itself.
 *
 * Stable id of a [`ProtocolEndpoint`].
 *
 * Stable id of a [`Provider`] (vendor namespace).
 */
type MCPServerID = string;

/**
 * Which MCP servers an agent uses — the management-plane agent↔MCP binding
 * (ADR-0043 Phase 3). References [`McpServerDef`]s by id; the resolver
 * materializes the referenced defs into [`ResolvedMcpServer`]s at run bind time.
 */
export interface AgentMCPConfig {
    agent_id:       string;
    mcp_server_ids: string[];
    version:        number;
    [property: string]: any;
}

/**
 * The "which credential" axis (oversight-next / awaken-management-contract).
 *
 * No credential is needed.
 *
 * Use exactly one source.
 *
 * Use one eligible member of a pool; the resolver selects by policy and may
 * fail over to the next member if the chosen one cannot be materialized.
 */
export interface CredentialBinding {
    type:                  Type;
    credential_source_id?: string;
    credential_pool_id?:   string;
    [property: string]: any;
}

export type Type = "none" | "exact" | "one_of_credential_pool";

/**
 * A pool of interchangeable credential sources for one provider principal
 * (oversight-next account grouping). The resolver picks one eligible member per
 * run; members are tried in policy order so a disabled/exhausted member fails
 * over to the next rather than failing the run (fail-closed only when none work).
 */
export interface CredentialPool {
    id:           string;
    members:      MemberElement[];
    workspace_id: string;
    [property: string]: any;
}

/**
 * One source's membership in a pool. `ordinal` is the default selection order
 * (ascending); a disabled member is skipped. `selection_weight` is reserved for a
 * future weighted policy and does not affect the default ordinal order.
 */
export interface MemberElement {
    credential_source_id: string;
    enabled:              boolean;
    ordinal:              number;
    selection_weight?:    number;
    [property: string]: any;
}

/**
 * One source's membership in a pool. `ordinal` is the default selection order
 * (ascending); a disabled member is skipped. `selection_weight` is reserved for a
 * future weighted policy and does not affect the default ordinal order.
 */
export interface CredentialPoolMember {
    credential_source_id: string;
    enabled:              boolean;
    ordinal:              number;
    selection_weight?:    number;
    [property: string]: any;
}

/**
 * The stored credential row — **secret-free** (the read/serde projection). The
 * secret is reachable only via `material_ref` through the [`SecretStore`].
 */
export interface CredentialSource {
    /**
     * Environment-variable name the secret is injected under (all kinds may set it).
     */
    env_key?: null | string;
    id:       string;
    kind:     CredentialKind;
    /**
     * Vault reference; `None` for `Env` (the secret never crosses the control plane).
     */
    material_ref?: null | string;
    /**
     * Provider namespace this credential authenticates (`anthropic`, `openai`).
     */
    provider_id?: null | string;
    status:       CredentialStatus;
    version:      number;
    workspace_id: string;
    [property: string]: any;
}

/**
 * Where a secret physically lives (the materialization axis).
 *
 * Secret material sealed in the vault (a [`SecretRef`] into [`SecretStore`]).
 *
 * A host environment variable named by `env_key`; nothing is stored here.
 */
export type CredentialKind = "vault" | "env";

/**
 * Lifecycle of a source.
 */
export type CredentialStatus = "active" | "disabled" | "archived";

/**
 * The secret-free result of a live credential probe.
 */
export interface CredentialValidation {
    adapter_kind: string;
    status:       Status;
    [property: string]: any;
}

/**
 * The result of a live credential probe (secret-free), aligned with the Managed
 * wire's `valid` / `invalid` / `unknown` statuses.
 */
export type Status = "valid" | "invalid" | "unknown";

/**
 * An authored "how to run this model" unit (ADR-0043 `InferenceProfile` /
 * oversight-next `ProviderIdentity`): it names the model, the credential binding
 * (vault-backed, never inline), and any endpoints the operator has toggled off.
 * The resolver reads it — it is never flowed into the runtime.
 */
export interface InferenceProfile {
    credential_binding:     InferenceProfileCredentialBinding;
    disabled_endpoint_ids?: string[];
    model_id:               string;
    [property: string]: any;
}

/**
 * The "which credential" axis (oversight-next / awaken-management-contract).
 *
 * No credential is needed.
 *
 * Use exactly one source.
 *
 * Use one eligible member of a pool; the resolver selects by policy and may
 * fail over to the next member if the chosen one cannot be materialized.
 */
export interface InferenceProfileCredentialBinding {
    type:                  Type;
    credential_source_id?: string;
    credential_pool_id?:   string;
    [property: string]: any;
}

/**
 * An authored MCP server definition (ADR-0043 Phase 3): where the server lives
 * and which credential authenticates to it. The binding is the same vault-backed
 * [`CredentialBinding`] inference uses (never an inline secret), so
 * `OneOfCredentialPool` failover applies to MCP credentials for free. The
 * resolver reads it — it is never flowed into the runtime.
 */
export interface MCPServerDef {
    credential_binding: MCPServerDefCredentialBinding;
    display_name:       string;
    id:                 string;
    url:                string;
    version:            number;
    [property: string]: any;
}

/**
 * The "which credential" axis (oversight-next / awaken-management-contract).
 *
 * No credential is needed.
 *
 * Use exactly one source.
 *
 * Use one eligible member of a pool; the resolver selects by policy and may
 * fail over to the next member if the chosen one cannot be materialized.
 */
export interface MCPServerDefCredentialBinding {
    type:                  Type;
    credential_source_id?: string;
    credential_pool_id?:   string;
    [property: string]: any;
}

/**
 * A model reachable on a protocol surface. `model_id` references the catalog's
 * `ModelSpec` (the intrinsic model attributes, owned by `awaken-agent-contract`).
 */
export interface Offering {
    flavor: ModelAPICompat;
    /**
     * The protocol-agnostic catalog model id (e.g. `claude-opus-4-8`).
     */
    model_id:             string;
    protocol_endpoint_id: string;
    provider_id:          string;
    /**
     * Provider-canonical model name sent upstream when it differs from `model_id`.
     */
    upstream_model?: null | string;
    [property: string]: any;
}

/**
 * The wire/model-API dialect a surface speaks. Replaces oversight's `WireFormat`;
 * the credential/model bindings are resolved against this flavor (ADR-0043).
 *
 * The `claude` adapter's wire.
 *
 * The `codex`/OpenAI chat wire.
 *
 * The Gemini wire.
 */
export type ModelAPICompat = "anthropic_messages" | "open_ai_chat" | "gemini";

/**
 * A concrete protocol surface of a provider: which wire + which URL. Distinct
 * flavors of one provider typically have distinct `base_url`s.
 */
export interface ProtocolEndpoint {
    /**
     * `http(s)` base URL override (proxy / self-hosted / compat endpoint).
     */
    base_url?:    null | string;
    display_name: string;
    flavor:       ModelAPICompat;
    id:           string;
    provider_id:  string;
    /**
     * Request timeout in seconds.
     */
    timeout_secs: number;
    version:      number;
    [property: string]: any;
}

/**
 * The catalog aggregate: providers, their endpoints, and the offerings across
 * them. The in-memory projection the resolver queries.
 */
export interface ProviderCatalog {
    endpoints: { [key: string]: EndpointValue };
    offerings: OfferingElement[];
    providers: { [key: string]: ProviderValue };
    [property: string]: any;
}

/**
 * A concrete protocol surface of a provider: which wire + which URL. Distinct
 * flavors of one provider typically have distinct `base_url`s.
 */
export interface EndpointValue {
    /**
     * `http(s)` base URL override (proxy / self-hosted / compat endpoint).
     */
    base_url?:    null | string;
    display_name: string;
    flavor:       ModelAPICompat;
    id:           string;
    provider_id:  string;
    /**
     * Request timeout in seconds.
     */
    timeout_secs: number;
    version:      number;
    [property: string]: any;
}

/**
 * A model reachable on a protocol surface. `model_id` references the catalog's
 * `ModelSpec` (the intrinsic model attributes, owned by `awaken-agent-contract`).
 */
export interface OfferingElement {
    flavor: ModelAPICompat;
    /**
     * The protocol-agnostic catalog model id (e.g. `claude-opus-4-8`).
     */
    model_id:             string;
    protocol_endpoint_id: string;
    provider_id:          string;
    /**
     * Provider-canonical model name sent upstream when it differs from `model_id`.
     */
    upstream_model?: null | string;
    [property: string]: any;
}

/**
 * A vendor namespace (`anthropic`, `openai`, …).
 */
export interface ProviderValue {
    display_name: string;
    id:           string;
    /**
     * URL-safe vendor slug, unique in the catalog.
     */
    slug: string;
    /**
     * Append-only version bumped on change.
     */
    version: number;
    [property: string]: any;
}

/**
 * A vendor namespace (`anthropic`, `openai`, …).
 */
export interface Provider {
    display_name: string;
    id:           string;
    /**
     * URL-safe vendor slug, unique in the catalog.
     */
    slug: string;
    /**
     * Append-only version bumped on change.
     */
    version: number;
    [property: string]: any;
}

/**
 * The **secret-free** result of a resolve (ADR-0043): the execution triple + the
 * adapter/endpoint it binds to, and whether a credential resolved — never the
 * secret itself. This is what an operator's "test binding" call sees.
 */
export interface ResolvedInferenceView {
    adapter_kind: string;
    base_url?:    null | string;
    /**
     * Whether a credential was materialized (never the value).
     */
    credential_present:   boolean;
    model_id:             string;
    protocol_endpoint_id: string;
    provider_id:          string;
    [property: string]: any;
}

/**
 * The **secret-free** projection of a resolved MCP server (ADR-0043): what the
 * agent's binding materializes to, and whether a credential resolved — never the
 * secret itself. This is what an operator's "test binding" call sees.
 */
export interface ResolvedMCPServerView {
    /**
     * Whether a credential was materialized (never the value).
     */
    credential_present: boolean;
    name:               string;
    url:                string;
    [property: string]: any;
}
