// GENERATED by scripts/contract/generate-contracts.sh — do not edit.
/**
 * Stable id of a [`CredentialSource`].
 *
 * A credential pool identifier.
 *
 * Stable id of a [`ProtocolEndpoint`].
 *
 * Stable id of a [`Provider`] (vendor namespace).
 */
type CredentialPoolID = string;

/**
 * An Agent's authored default inputs. The repository supplies Workspace as the
 * aggregate key, so this value contains only Agent-local configuration. The same
 * typed [`InputBinding`] language is used by Session attachments; no authorization
 * subject, policy, API key, secret, content pin, Project, or WorkUnit enters it.
 */
export interface AgentInputConfig {
    agent_id: string;
    /**
     * Exact Environment revision selected as this Agent's Session default.
     * It is secret-free and shares the same CAS revision as Resource bindings,
     * so callers cannot observe a mixed default bundle.
     */
    environment?: null | EnvironmentObject;
    inputs:       InputElement[];
    revision:     number;
    [property: string]: unknown;
}

export interface EnvironmentObject {
    environment_id: string;
    revision:       number;
    [property: string]: unknown;
}

export interface InputElement {
    access:        Access;
    binding_id:    string;
    instructions?: null | string;
    mount_path:    string;
    target:        InputTarget;
    [property: string]: unknown;
}

export type Access = "read_only" | "read_write";

export interface InputTarget {
    id:   string;
    kind: TargetKind;
    [property: string]: unknown;
}

export type TargetKind = "file" | "memory_store" | "repository";

/**
 * RFC 9457 Problem Details with stable application extension members (`code`, `request_id`,
 * `details`, `errors`).
 */
export interface APIError {
    /**
     * Stable application error code; clients may branch on this.
     */
    code: string;
    /**
     * Request-specific human-readable explanation.
     */
    detail?: string;
    /**
     * Type-specific structured metadata.
     */
    details?: unknown;
    /**
     * Field/query/header violations for validation-style problems.
     */
    errors?:   Error[];
    instance?: string;
    /**
     * Correlation id echoed from the `x-request-id` header.
     */
    request_id: string;
    status:     number;
    /**
     * Stable human-readable summary for this problem type.
     */
    title: string;
    /**
     * URI reference identifying the problem type.
     */
    type: string;
    [property: string]: unknown;
}

export interface Error {
    code:     string;
    field:    string;
    message?: string;
    [property: string]: unknown;
}

/**
 * The availability of one credential source at a point in time.
 *
 * Selectable now.
 *
 * Cooled by a transient quota/rate signal until `retry_at_ms`; selectable
 * again at or after that wall-clock deadline (auto-resume, no timer).
 *
 * Cooled by a hard exhaustion with no known reset — excluded until explicitly
 * [`cleared`](AvailabilityLedger::clear) (e.g. a fresh availability check
 * passes).
 */
export interface AvailabilityState {
    state:        State;
    retry_at_ms?: number;
    [property: string]: unknown;
}

export type State = "available" | "cooled_down" | "exhausted";

/**
 * Durable outcome of reconciling one complete provider model listing.
 */
export interface CatalogSyncResult {
    activated:          number;
    discovered:         number;
    marked_unavailable: number;
    /**
     * Observation time shared by every row in this successful atomic refresh.
     */
    observed_at_unix_ms: number;
    [property: string]: unknown;
}

/**
 * Stable frontend/SDK feature discovery; callers never infer deployment
 * posture from a failed Cloud request.
 */
export interface ConfigCapabilitiesView {
    identity: Identity;
    models:   Models;
    surfaces: Surfaces;
    [property: string]: unknown;
}

export interface Identity {
    authenticated:       boolean;
    cloud_login_enabled: boolean;
    mode:                string;
    [property: string]: unknown;
}

export interface Models {
    byok_enabled:              boolean;
    cloud_models_enabled:      boolean;
    local_catalog_enabled:     boolean;
    profile_authoring_enabled: boolean;
    [property: string]: unknown;
}

/**
 * Product surfaces actually mounted by the same-origin process composition.
 * This is presentation discovery only; mounted routes retain their own PEP.
 */
export interface Surfaces {
    access_management: boolean;
    managed_runtime:   boolean;
    [property: string]: unknown;
}

/**
 * A cooldown signal an operator (or an external rate-limit integration) records
 * against a credential source. `kind` maps to a failure
 * [`Disposition`](awaken_runtime_contract::resilience::Disposition): `quota` cools
 * until `retry_after_secs` (or a default window); `exhausted` cools until cleared;
 * `available` / `clear` lifts any cooldown; `transient` / `permanent` are no-ops on
 * availability (they are retry/next-binding decisions, not identity cooldowns).
 */
export interface CooldownRequest {
    kind:              string;
    retry_after_secs?: number | null;
    [property: string]: unknown;
}

/**
 * The "which credential" axis (oversight-next / awaken-management-contract).
 *
 * No credential is needed.
 *
 * Obtain short-lived, exact-model access from the platform broker at
 * execution time. No Provider credential or Cloud capability is persisted
 * in the local profile or publication.
 *
 * Use exactly one source.
 *
 * Use one eligible member of a pool; the resolver selects by policy and may
 * fail over to the next member if the chosen one cannot be materialized.
 */
export interface CredentialBinding {
    type:                  Type;
    credential_source_id?: string;
    credential_pool_id?:   string;
    [property: string]: unknown;
}

export type Type = "none" | "brokered" | "exact" | "one_of_credential_pool";

/**
 * A pool of interchangeable credential sources for one provider principal
 * (oversight-next account grouping). The resolver picks one eligible member per
 * run; members are tried in policy order so a disabled/exhausted member fails
 * over to the next rather than failing the run (fail-closed only when none work).
 */
export interface CredentialPool {
    id:      string;
    members: MemberElement[];
    /**
     * How the selector picks among eligible members. `#[serde(default)]` keeps
     * existing pool rows (persisted as JSON) loadable as [`FirstHealthy`], the
     * historical behavior.
     *
     * [`FirstHealthy`]: SelectionPolicy::FirstHealthy
     */
    policy?:      Policy;
    workspace_id: string;
    [property: string]: unknown;
}

/**
 * One source's membership in a pool. `ordinal` is the default selection order
 * (ascending); a disabled member is skipped. `selection_weight` is reserved for a
 * future weighted policy and does not affect the default ordinal order.
 */
export interface MemberElement {
    credential_source_id: string;
    enabled:              boolean;
    ordinal:              number;
    selection_weight?:    number;
    [property: string]: unknown;
}

/**
 * How the selector picks among eligible members. `#[serde(default)]` keeps
 * existing pool rows (persisted as JSON) loadable as [`FirstHealthy`], the
 * historical behavior.
 *
 * [`FirstHealthy`]: SelectionPolicy::FirstHealthy
 *
 * How a pool picks among its eligible members — the *intent* behind selection,
 * consumed by the runtime selector (an availability-aware picker, per ADR-0043).
 * The pool's [`selection_order`](CredentialPool::selection_order) always yields the
 * eligible members in ordinal order; this policy decides which of them the picker
 * commits to.
 *
 * Names align with awaken-next's `SelectionPolicy`. `#[non_exhaustive]` so adding a
 * policy is not a breaking change.
 *
 * Pin the first eligible member in ordinal order (the default; the historical
 * behavior). Deterministic — the same pool state always picks the same member.
 *
 * Round-robin across the eligible members to spread load and delay quota
 * exhaustion. Rotation state lives in the selector, not the pool.
 *
 * Reuse the member a prior run in the same scope committed to, when it is still
 * eligible, for prompt-cache / session affinity.
 */
export type Policy = "first_healthy" | "rotate_spread" | "sticky_resume";

/**
 * One source's membership in a pool. `ordinal` is the default selection order
 * (ascending); a disabled member is skipped. `selection_weight` is reserved for a
 * future weighted policy and does not affect the default ordinal order.
 */
export interface CredentialPoolMember {
    credential_source_id: string;
    enabled:              boolean;
    ordinal:              number;
    selection_weight?:    number;
    [property: string]: unknown;
}

/**
 * Secret-free credential projection. Internal token-source argv and vault refs
 * never cross the admin boundary; consumers bind this stable source id.
 */
export interface CredentialSourceView {
    env_key?:              null | string;
    id:                    string;
    kind:                  CredentialKind;
    oauth_helper?:         CredentialSource | null;
    protocol_endpoint_id?: null | string;
    provider_id?:          null | string;
    status:                CredentialStatus;
    version:               number;
    workspace_id:          string;
    [property: string]: unknown;
}

/**
 * Where a secret physically lives (the materialization axis).
 *
 * Secret material sealed in the vault (a [`SecretRef`] into [`SecretStore`]).
 *
 * Legacy persisted value. New sources of this kind are rejected and existing
 * rows cannot materialize: environment discovery may propose configuration,
 * but an operator must persist it as `Vault` before publication/execution.
 *
 * An OAuth-backed provider credential (#5): the secret is a short-lived
 * Bearer token minted on demand by running `oauth_command`, never stored. The
 * long-lived grant lives inside the helper (e.g. `gcloud`), so nothing secret
 * crosses the control plane.
 *
 * Secret material is installed and retained on an eligible worker. The
 * persisted source id and revision are the only cross-plane handle; worker
 * heartbeats advertise whether that exact handle is currently available.
 */
export type CredentialKind = "vault" | "env" | "oauth" | "worker_local";

/**
 * Server-owned OAuth token helper. The API carries this allowlisted id, never
 * an operator-supplied command line; the credential bounded context owns how
 * it becomes a token source for model, MCP, and A2A consumers alike.
 *
 * Mint a Google access token from the active gcloud account.
 */
export type CredentialSource = "gcloud";

/**
 * Lifecycle of a source.
 */
export type CredentialStatus = "active" | "disabled" | "archived";

/**
 * The secret-free result of a live credential probe.
 */
export interface CredentialValidation {
    adapter_kind: string;
    status:       CredentialValidationStatus;
    [property: string]: unknown;
}

/**
 * The result of a live credential probe (secret-free), aligned with the Managed
 * wire's `valid` / `invalid` / `unknown` statuses.
 */
export type CredentialValidationStatus = "valid" | "invalid" | "unknown";

/**
 * The credential-entry wire body. `secret` is write-only: it is sealed into the
 * [`SecretStore`] and never appears on any response (the returned row is
 * secret-free). `RedactedString` is intentionally not `Deserialize`, so the raw
 * secret crosses the wire exactly once, here.
 */
export interface EnterCredentialRequest {
    env_key?: null | string;
    kind:     CredentialKind;
    /**
     * Structured material sealed as one versioned Vault document. Mutually
     * exclusive with the legacy `secret` field.
     */
    material?: null | MaterialObject;
    /**
     * A server-owned OAuth refresh helper. This is an allowlisted identifier,
     * never an operator-supplied command line.
     */
    oauth_helper?: CredentialSource | null;
    provider_id?:  null | string;
    /**
     * The secret to seal — required for `vault`. Environment-backed credentials
     * are not accepted; environment discovery is exposed only as proposals.
     */
    secret?:      null | string;
    workspace_id: string;
    [property: string]: unknown;
}

export interface MaterialObject {
    /**
     * Opaque named secret fields. Core stores and transports them but never
     * assign protocol meaning; the matching consumer owns validation.
     */
    fields: { [key: string]: string };
    /**
     * Namespaced, versioned type owned by the installed consumer extension,
     * for example `acme.ssh-key/v1`.
     */
    type_id: string;
    [property: string]: unknown;
}

export interface ExecutableModelOption {
    backend_ref: string;
    dialect:     string;
    endpoint_id: string;
    model_id:    string;
    provider_id: string;
    readiness:   ExecutableModelReadiness;
    [property: string]: unknown;
}

export type ExecutableModelReadiness = "ready" | "offering_unavailable" | "credential_unavailable" | "runtime_unavailable" | "dialect_unavailable";

/**
 * An authored "how to run this model" unit: it names an exact primary and
 * ordered fallback candidates, each with a vault-backed (never inline)
 * credential binding, plus endpoints the operator has toggled off. The resolver
 * reads it — it is never flowed into the runtime.
 */
export interface InferenceProfile {
    disabled_endpoint_ids?: string[];
    /**
     * Explicit alternates, tried in authored order. The resolver never appends an
     * implicit Cloud, BYOK, or local fallback.
     */
    fallbacks?: PrimaryElement[];
    /**
     * Exact preferred offering. Provider and endpoint qualifiers prevent a model
     * id shared by BYOK and Cloud sources from becoming ambiguous at runtime.
     */
    primary: PrimaryElement;
    /**
     * Owning workspace, stamped by the trusted configuration edge. An empty
     * value represents an unstamped domain value and is never treated as owned.
     */
    workspace_id?: string;
}

/**
 * One explicit step in a profile's failover chain. Binding credentials per
 * target allows a BYOK primary and Cloud fallback (or the reverse) without ever
 * guessing which identity may authenticate which provider.
 *
 * Exact preferred offering. Provider and endpoint qualifiers prevent a model
 * id shared by BYOK and Cloud sources from becoming ambiguous at runtime.
 */
export interface PrimaryElement {
    credential_binding: CredentialBindingObject;
    target:             PrimaryTarget;
    [property: string]: unknown;
}

/**
 * The "which credential" axis (oversight-next / awaken-management-contract).
 *
 * No credential is needed.
 *
 * Obtain short-lived, exact-model access from the platform broker at
 * execution time. No Provider credential or Cloud capability is persisted
 * in the local profile or publication.
 *
 * Use exactly one source.
 *
 * Use one eligible member of a pool; the resolver selects by policy and may
 * fail over to the next member if the chosen one cannot be materialized.
 */
export interface CredentialBindingObject {
    type:                  Type;
    credential_source_id?: string;
    credential_pool_id?:   string;
    [property: string]: unknown;
}

/**
 * Stable authoring identity used to select one catalog Offering.
 *
 * `endpoint_name` is the human qualifier used by public model ids. Resolution
 * maps it to a concrete endpoint after dialect negotiation. Exact config and
 * profile authoring may instead use `protocol_endpoint_id`; admission rejects
 * a target containing both.
 */
export interface PrimaryTarget {
    endpoint_name?:        null | string;
    model_id:              string;
    protocol_endpoint_id?: null | string;
    provider_id?:          null | string;
    [property: string]: unknown;
}

/**
 * The published intrinsic attributes of a catalog model, keyed by `model_id`. This is
 * the control plane's OWN projection of what a console publishes — deliberately not the
 * agent-domain `ModelSpec` (a runtime type the control plane must not depend on, per the
 * dependency-direction ban); it carries only what the catalog's consumers read. Extended
 * as the console publishes more attributes.
 */
export interface ModelAttributes {
    /**
     * Max context window in tokens — the single budget both the ACP CLIs' auto-compact
     * window and the native compaction ext derive from. Absent → the consumer falls back.
     */
    context_window?: number | null;
    /**
     * Max output tokens the model emits, when published.
     */
    max_output_tokens?: number | null;
    /**
     * Field-level origin. Values stay flat and convenient for runtime consumers;
     * management surfaces use this map to explain whether each fact was authored,
     * observed from a provider API, or supplied by Awaken's curated registry.
     */
    provenance?: { [key: string]: ProvenanceValue };
    [property: string]: unknown;
}

/**
 * Explainability metadata for one field in [`ModelAttributes`].
 */
export interface ProvenanceValue {
    observed_at_unix_ms: number;
    source:              ProvenanceSource;
    [property: string]: unknown;
}

/**
 * Authority behind one published model-attribute value.
 */
export type ProvenanceSource = "manual" | "provider_api" | "curated" | "brokered";

export interface ModelSelection {
    mode:                   Mode;
    profile_id?:            string;
    backend_ref?:           string;
    configuration?:         Tion;
    target?:                ModelSelectionTarget;
    model_ref?:             string;
    provider_identity_ref?: string;
}

/**
 * Adapter-native ACP Session intent attached to an Agent model selection.
 *
 * Values remain strings because the selected ACP runtime's negotiated
 * capability descriptor is the authority that validates supported modes and
 * option values at publication time.
 */
export interface Tion {
    mode?:    null | string;
    options?: { [key: string]: string };
}

export type Mode = "auto" | "profile" | "target" | "backend_default" | "backend_exact" | "pinned";

/**
 * Stable authoring identity used to select one catalog Offering.
 *
 * `endpoint_name` is the human qualifier used by public model ids. Resolution
 * maps it to a concrete endpoint after dialect negotiation. Exact config and
 * profile authoring may instead use `protocol_endpoint_id`; admission rejects
 * a target containing both.
 */
export interface ModelSelectionTarget {
    endpoint_name?:        null | string;
    model_id:              string;
    protocol_endpoint_id?: null | string;
    provider_id?:          null | string;
    [property: string]: unknown;
}

/**
 * Stable authoring identity used to select one catalog Offering.
 *
 * `endpoint_name` is the human qualifier used by public model ids. Resolution
 * maps it to a concrete endpoint after dialect negotiation. Exact config and
 * profile authoring may instead use `protocol_endpoint_id`; admission rejects
 * a target containing both.
 */
export interface ModelTarget {
    endpoint_name?:        null | string;
    model_id:              string;
    protocol_endpoint_id?: null | string;
    provider_id?:          null | string;
    [property: string]: unknown;
}

/**
 * A model reachable on a protocol surface. `model_id` references the catalog's
 * [`ModelAttributes`] (the intrinsic model attributes the control plane publishes).
 */
export interface Offering {
    dialect: APIDialect;
    /**
     * Unix timestamp (milliseconds) of the most recent complete provider listing
     * that contained this route. Manual offerings never carry this observation.
     * When a later complete listing omits the model, the timestamp is retained so
     * operators can distinguish "last seen then" from "never observed".
     */
    last_seen_at_unix_ms?: number | null;
    /**
     * The protocol-agnostic catalog model id (e.g. `claude-opus-4-8`).
     */
    model_id:             string;
    protocol_endpoint_id: string;
    provider_id:          string;
    /**
     * Who owns the catalog fact. Manually authored rows are never demoted by a
     * provider refresh; provider-discovered rows follow the provider's latest
     * complete listing.
     */
    source?: OfferingSource;
    /**
     * Whether this route may be selected for a new publication. Provider sync is
     * non-destructive: a missing discovered model becomes unavailable instead of
     * being deleted, so existing immutable publications remain explainable.
     */
    status?: OfferingStatus;
    /**
     * Provider-canonical model name sent upstream when it differs from `model_id`.
     */
    upstream_model?: null | string;
    [property: string]: unknown;
}

/**
 * The wire/model-API dialect a surface speaks. Replaces oversight's `WireFormat`;
 * the credential/model bindings are resolved against this dialect (ADR-0043).
 *
 * The `claude` adapter's wire.
 *
 * The `codex`/OpenAI chat wire.
 *
 * The OpenAI Responses API wire. This remains distinct from Chat
 * Completions even though both are served by the OpenAI adapter family.
 *
 * The Gemini wire.
 *
 * Gemini on Vertex AI: native Gemini payloads with OAuth Bearer auth and
 * a project/location endpoint.
 */
export type APIDialect = "anthropic_messages" | "open_ai_chat" | "open_ai_responses" | "gemini" | "vertex_gemini";

/**
 * Who owns the catalog fact. Manually authored rows are never demoted by a
 * provider refresh; provider-discovered rows follow the provider's latest
 * complete listing.
 *
 * Authority that published an [`Offering`].
 *
 * Explicit UI/API authoring is authoritative over provider discovery.
 *
 * Observed from the configured endpoint's provider API.
 *
 * Rebuildable projection of an authenticated managed model service. Access
 * is authorized just in time; the catalog row carries no entitlement,
 * Provider credential, internal route, or pricing fact.
 */
export type OfferingSource = "manual" | "provider_api" | "brokered";

/**
 * Whether this route may be selected for a new publication. Provider sync is
 * non-destructive: a missing discovered model becomes unavailable instead of
 * being deleted, so existing immutable publications remain explainable.
 *
 * Admission status for new publications using an offering.
 */
export type OfferingStatus = "active" | "unavailable";

/**
 * Which members of a pool are selectable right now — `selection_order` with cooled
 * members dropped (`eligible_order`). The ops view of the mid-run rotation.
 */
export interface PoolEligibleView {
    cooled:   string[];
    eligible: string[];
    [property: string]: unknown;
}

/**
 * A concrete protocol surface of a provider: which wire + which URL. Distinct
 * flavors of one provider typically have distinct `base_url`s.
 */
export interface ProtocolEndpoint {
    /**
     * `http(s)` base URL override (proxy / self-hosted / compat endpoint).
     */
    base_url?:    null | string;
    dialect:      APIDialect;
    display_name: string;
    id:           string;
    provider_id:  string;
    /**
     * Request timeout in seconds.
     */
    timeout_secs: number;
    version:      number;
    [property: string]: unknown;
}

/**
 * A vendor namespace (`anthropic`, `openai`, …).
 */
export interface Provider {
    display_name: string;
    id:           string;
    /**
     * URL-safe vendor slug, unique in the catalog.
     */
    slug: string;
    /**
     * Append-only version bumped on change.
     */
    version: number;
    [property: string]: unknown;
}

/**
 * The catalog aggregate: providers, their endpoints, and the offerings across
 * them. The in-memory projection the resolver queries.
 */
export interface ProviderCatalog {
    endpoints: { [key: string]: EndpointValue };
    /**
     * The published attributes of the models the offerings reference, keyed by
     * `model_id`. Absent for a model whose attributes aren't published (the consumer
     * then falls back — e.g. compaction stays message-count based).
     */
    model_attributes?: { [key: string]: ModelAttributeValue };
    offerings:         OfferingElement[];
    providers:         { [key: string]: ProviderValue };
    [property: string]: unknown;
}

/**
 * A concrete protocol surface of a provider: which wire + which URL. Distinct
 * flavors of one provider typically have distinct `base_url`s.
 */
export interface EndpointValue {
    /**
     * `http(s)` base URL override (proxy / self-hosted / compat endpoint).
     */
    base_url?:    null | string;
    dialect:      APIDialect;
    display_name: string;
    id:           string;
    provider_id:  string;
    /**
     * Request timeout in seconds.
     */
    timeout_secs: number;
    version:      number;
    [property: string]: unknown;
}

/**
 * The published intrinsic attributes of a catalog model, keyed by `model_id`. This is
 * the control plane's OWN projection of what a console publishes — deliberately not the
 * agent-domain `ModelSpec` (a runtime type the control plane must not depend on, per the
 * dependency-direction ban); it carries only what the catalog's consumers read. Extended
 * as the console publishes more attributes.
 */
export interface ModelAttributeValue {
    /**
     * Max context window in tokens — the single budget both the ACP CLIs' auto-compact
     * window and the native compaction ext derive from. Absent → the consumer falls back.
     */
    context_window?: number | null;
    /**
     * Max output tokens the model emits, when published.
     */
    max_output_tokens?: number | null;
    /**
     * Field-level origin. Values stay flat and convenient for runtime consumers;
     * management surfaces use this map to explain whether each fact was authored,
     * observed from a provider API, or supplied by Awaken's curated registry.
     */
    provenance?: { [key: string]: ProvenanceObject };
    [property: string]: unknown;
}

/**
 * Explainability metadata for one field in [`ModelAttributes`].
 */
export interface ProvenanceObject {
    observed_at_unix_ms: number;
    source:              ProvenanceSource;
    [property: string]: unknown;
}

/**
 * A model reachable on a protocol surface. `model_id` references the catalog's
 * [`ModelAttributes`] (the intrinsic model attributes the control plane publishes).
 */
export interface OfferingElement {
    dialect: APIDialect;
    /**
     * Unix timestamp (milliseconds) of the most recent complete provider listing
     * that contained this route. Manual offerings never carry this observation.
     * When a later complete listing omits the model, the timestamp is retained so
     * operators can distinguish "last seen then" from "never observed".
     */
    last_seen_at_unix_ms?: number | null;
    /**
     * The protocol-agnostic catalog model id (e.g. `claude-opus-4-8`).
     */
    model_id:             string;
    protocol_endpoint_id: string;
    provider_id:          string;
    /**
     * Who owns the catalog fact. Manually authored rows are never demoted by a
     * provider refresh; provider-discovered rows follow the provider's latest
     * complete listing.
     */
    source?: OfferingSource;
    /**
     * Whether this route may be selected for a new publication. Provider sync is
     * non-destructive: a missing discovered model becomes unavailable instead of
     * being deleted, so existing immutable publications remain explainable.
     */
    status?: OfferingStatus;
    /**
     * Provider-canonical model name sent upstream when it differs from `model_id`.
     */
    upstream_model?: null | string;
    [property: string]: unknown;
}

/**
 * A vendor namespace (`anthropic`, `openai`, …).
 */
export interface ProviderValue {
    display_name: string;
    id:           string;
    /**
     * URL-safe vendor slug, unique in the catalog.
     */
    slug: string;
    /**
     * Append-only version bumped on change.
     */
    version: number;
    [property: string]: unknown;
}

export interface ProviderConnectionSummary {
    active_credentials:    number;
    active_models:         number;
    display_name:          string;
    endpoint_ids:          string[];
    last_seen_at_unix_ms?: number | null;
    provider_id:           string;
    status:                ProviderConnectionSummaryStatus;
    unavailable_models:    number;
    [property: string]: unknown;
}

export type ProviderConnectionSummaryStatus = "not_configured" | "connected" | "ready" | "stale" | "needs_attention" | "unavailable";

export interface ProviderConnectionView {
    credential: Credential;
    endpoint:   Endpoint;
    provider:   ProviderObject;
    sync:       Sync;
    [property: string]: unknown;
}

/**
 * Secret-free credential projection. Internal token-source argv and vault refs
 * never cross the admin boundary; consumers bind this stable source id.
 */
export interface Credential {
    env_key?:              null | string;
    id:                    string;
    kind:                  CredentialKind;
    oauth_helper?:         CredentialSource | null;
    protocol_endpoint_id?: null | string;
    provider_id?:          null | string;
    status:                CredentialStatus;
    version:               number;
    workspace_id:          string;
    [property: string]: unknown;
}

/**
 * A concrete protocol surface of a provider: which wire + which URL. Distinct
 * flavors of one provider typically have distinct `base_url`s.
 */
export interface Endpoint {
    /**
     * `http(s)` base URL override (proxy / self-hosted / compat endpoint).
     */
    base_url?:    null | string;
    dialect:      APIDialect;
    display_name: string;
    id:           string;
    provider_id:  string;
    /**
     * Request timeout in seconds.
     */
    timeout_secs: number;
    version:      number;
    [property: string]: unknown;
}

/**
 * A vendor namespace (`anthropic`, `openai`, …).
 */
export interface ProviderObject {
    display_name: string;
    id:           string;
    /**
     * URL-safe vendor slug, unique in the catalog.
     */
    slug: string;
    /**
     * Append-only version bumped on change.
     */
    version: number;
    [property: string]: unknown;
}

/**
 * Durable outcome of reconciling one complete provider model listing.
 */
export interface Sync {
    activated:          number;
    discovered:         number;
    marked_unavailable: number;
    /**
     * Observation time shared by every row in this successful atomic refresh.
     */
    observed_at_unix_ms: number;
    [property: string]: unknown;
}

/**
 * One supported provider driver's authoring capabilities. The list returned by
 * [`provider_driver_descriptors`] is the single source used by API clients to
 * render provider cards and forms.
 */
export interface ProviderDriverDescriptor {
    auth_methods:             AuthMethodElement[];
    configuration_fields:     ConfigurationFieldElement[];
    default_endpoints:        DefaultEndpointElement[];
    display_name:             string;
    documentation_url?:       null | string;
    provider_kind:            string;
    supported_dialects:       APIDialect[];
    supports_model_discovery: boolean;
    [property: string]: unknown;
}

/**
 * Authentication input a provider connection can request. This describes the
 * authoring UI only; credential material remains owned by the vault.
 */
export type AuthMethodElement = "api_key" | "oauth";

export interface ConfigurationFieldElement {
    advanced:     boolean;
    key:          string;
    kind:         ConfigurationFieldKind;
    label:        string;
    placeholder?: null | string;
    required:     boolean;
    [property: string]: unknown;
}

/**
 * Input widget rendered from a provider descriptor. Descriptors are static
 * adapter capabilities, not user configuration and not another model catalog.
 */
export type ConfigurationFieldKind = "secret" | "text" | "url";

export interface DefaultEndpointElement {
    base_url: string;
    dialect:  APIDialect;
    /**
     * Optional provider-owned model-directory base when discovery is exposed
     * separately from the inference protocol surface.
     */
    model_discovery_base_url?: null | string;
    [property: string]: unknown;
}

/**
 * Secret-free authoring input. Provenance is intentionally absent: external
 * callers cannot claim that a manual value came from a provider or curated source.
 */
export interface PutModelAttributesRequest {
    context_window?:    number | null;
    max_output_tokens?: number | null;
}

/**
 * Resolve an authored profile within a workspace's credential scope.
 */
export interface ResolveProfileRequest {
    workspace_id: string;
    [property: string]: unknown;
}

/**
 * A dry-run resolve request. An unqualified target is valid when the model id
 * identifies exactly one active offering; callers always use the same target shape.
 */
export interface ResolveRequest {
    binding:      Binding;
    target:       ResolveRequestTarget;
    workspace_id: string;
}

/**
 * The "which credential" axis (oversight-next / awaken-management-contract).
 *
 * No credential is needed.
 *
 * Obtain short-lived, exact-model access from the platform broker at
 * execution time. No Provider credential or Cloud capability is persisted
 * in the local profile or publication.
 *
 * Use exactly one source.
 *
 * Use one eligible member of a pool; the resolver selects by policy and may
 * fail over to the next member if the chosen one cannot be materialized.
 */
export interface Binding {
    type:                  Type;
    credential_source_id?: string;
    credential_pool_id?:   string;
    [property: string]: unknown;
}

/**
 * Stable authoring identity used to select one catalog Offering.
 *
 * `endpoint_name` is the human qualifier used by public model ids. Resolution
 * maps it to a concrete endpoint after dialect negotiation. Exact config and
 * profile authoring may instead use `protocol_endpoint_id`; admission rejects
 * a target containing both.
 */
export interface ResolveRequestTarget {
    endpoint_name?:        null | string;
    model_id:              string;
    protocol_endpoint_id?: null | string;
    provider_id?:          null | string;
    [property: string]: unknown;
}

/**
 * The ordered candidate list a profile resolves to (E3-2): one secret-free view per
 * model in the profile's axis, in failover order.
 */
export interface ResolvedCandidatesView {
    candidates: CandidateElement[];
    [property: string]: unknown;
}

/**
 * The **secret-free** result of a resolve (ADR-0043): the execution triple + the
 * adapter/endpoint it binds to, and whether a credential resolved — never the
 * secret itself. This is what an operator's "test binding" call sees.
 */
export interface CandidateElement {
    adapter_kind: string;
    base_url?:    null | string;
    /**
     * Whether a credential was materialized (never the value).
     */
    credential_present:   boolean;
    model_id:             string;
    protocol_endpoint_id: string;
    provider_id:          string;
    [property: string]: unknown;
}

/**
 * The **secret-free** result of a resolve (ADR-0043): the execution triple + the
 * adapter/endpoint it binds to, and whether a credential resolved — never the
 * secret itself. This is what an operator's "test binding" call sees.
 */
export interface ResolvedInferenceView {
    adapter_kind: string;
    base_url?:    null | string;
    /**
     * Whether a credential was materialized (never the value).
     */
    credential_present:   boolean;
    model_id:             string;
    protocol_endpoint_id: string;
    provider_id:          string;
    [property: string]: unknown;
}

/**
 * Rotate the primary material of one exact active Vault credential revision.
 * The secret is write-only and the response remains a secret-free source view.
 */
export interface RotateCredentialRequest {
    expected_version: number;
    secret:           string;
    [property: string]: unknown;
}

export interface SaveProviderConnectionRequest {
    base_url?:      null | string;
    configuration?: { [key: string]: string };
    /**
     * Reuse one active Workspace credential instead of creating a duplicate.
     */
    credential_source_id?: null | string;
    dialect:               APIDialect;
    display_name:          string;
    /**
     * Optional stable qualifier for a second endpoint using the same dialect.
     */
    endpoint_name?:  null | string;
    idempotency_key: string;
    /**
     * Server-owned OAuth helper used to mint a short-lived token for both the
     * pre-save discovery and the persisted credential source.
     */
    oauth_helper?: CredentialSource | null;
    provider_id:   string;
    /**
     * Write-only API key. Exactly one of `secret`, `oauth_helper`, or
     * `credential_source_id` must be supplied; the connection command is the
     * one authoring path for every supported credential source.
     */
    secret?:       null | string;
    timeout_secs?: number;
    workspace_id:  string;
    [property: string]: unknown;
}

/**
 * Live-validate a credential against a model's resolved provider endpoint.
 */
export interface ValidateCredentialRequest {
    model_id:     string;
    workspace_id: string;
    [property: string]: unknown;
}
