// GENERATED by scripts/contract/generate-contracts.sh — do not edit.
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ModelSelection =
  | {
      mode: "auto";
    }
  | {
      mode: "profile";
      profile_id: string;
    }
  | {
      backend_ref: string;
      configuration?: AcpSessionConfiguration;
      mode: "backend_default";
    }
  | {
      backend_ref: string;
      configuration?: AcpSessionConfiguration;
      mode: "backend_exact";
      model_ref: string;
    }
  | {
      backend_ref: string;
      mode: "pinned";
      model_ref: string;
      provider_identity_ref: string;
    };

/**
 * Adapter-native ACP Session intent frozen with one BackendOwned candidate.
 * Omission preserves backend defaults; no discovered schema is copied here.
 */
export interface AcpSessionConfiguration {
  mode?: string | null;
  options?: {
    [k: string]: string;
  };
  [k: string]: unknown;
}
