// GENERATED by scripts/contract/generate-contracts.sh — do not edit.
/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ModelSelection =
  | {
      mode: "auto";
    }
  | {
      mode: "profile";
      profile_id: string;
    }
  | {
      backend_ref: string;
      configuration?: AcpSessionConfiguration;
      mode: "target";
      target: ModelTarget;
    }
  | {
      backend_ref: string;
      configuration?: AcpSessionConfiguration;
      mode: "backend_default";
    }
  | {
      backend_ref: string;
      configuration?: AcpSessionConfiguration;
      mode: "backend_exact";
      model_ref: string;
    }
  | {
      backend_ref: string;
      mode: "pinned";
      model_ref: string;
      provider_identity_ref: string;
    };

/**
 * Adapter-native ACP Session intent attached to an Agent model selection.
 *
 * Values remain strings because the selected ACP runtime's negotiated
 * capability descriptor is the authority that validates supported modes and
 * option values at publication time.
 */
export interface AcpSessionConfiguration {
  mode?: string | null;
  options?: {
    [k: string]: string;
  };
  /**
   * Portable path relative to the Session workspace. The host maps it to the
   * environment's interior root before sending ACP `session/new.cwd`.
   */
  working_directory?: string | null;
}
/**
 * Stable authoring identity used to select one catalog Offering.
 *
 * `endpoint_name` is the human qualifier used by public model ids. Resolution
 * maps it to a concrete endpoint after dialect negotiation. Exact config and
 * profile authoring may instead use `protocol_endpoint_id`; admission rejects
 * a target containing both.
 */
export interface ModelTarget {
  /**
   * Public API-dialect qualifier (for example `anthropic_messages` or
   * `open_ai_responses`). It narrows a provider's protocol surfaces without
   * exposing the catalog's internal endpoint identity.
   */
  api_dialect?: string | null;
  endpoint_name?: string | null;
  model_id: string;
  protocol_endpoint_id?: string | null;
  provider_id?: string | null;
  [k: string]: unknown;
}
