// Machine-owned method-level evidence for the official TypeScript Managed SDK.
// Every public leaf has a real behavior owner plus stable negative/auth case ids.

const group = (prefix, route, owner, methods, overrides = {}) =>
  methods.map((method) => {
    const sdkMethod = `${prefix}.${method}`;
    return {
      sdkMethod,
      route,
      owner: overrides[method] ?? owner,
      happy: `${sdkMethod}:happy`,
      missing: `${sdkMethod}:missing`,
      invalidState: `${sdkMethod}:invalid-state`,
      authWorkspace: `${sdkMethod}:auth-workspace`,
    };
  });

export const MANAGED_TS_METHOD_MANIFEST = [
  ...group('models', '/v1/models', 'management_files_models_e2e.mjs', ['retrieve', 'list']),
  ...group('agents', '/v1/agents', 'management_agents_e2e.mjs',
    ['create', 'retrieve', 'update', 'list', 'archive']),
  ...group('agents.versions', '/v1/agents/{agent_id}/versions', 'management_agents_e2e.mjs', ['list']),
  ...group('environments', '/v1/environments', 'management_environments_e2e.mjs',
    ['create', 'retrieve', 'update', 'list', 'delete', 'archive']),
  ...group('environments.work', '/v1/environments/{environment_id}/work',
    'management_environment_work_depth_e2e.mjs',
    ['retrieve', 'update', 'list', 'ack', 'heartbeat', 'poll', 'stats', 'stop', 'poller', 'worker'],
    {
      poller: 'management_official_worker_e2e.mjs',
      worker: 'management_environment_worker_full_e2e.mjs',
    }),
  ...group('sessions', '/v1/sessions', 'management_sessions_family_e2e.mjs',
    ['create', 'retrieve', 'update', 'list', 'delete', 'archive']),
  ...group('sessions.events', '/v1/sessions/{session_id}/events', 'managed_e2e.mjs',
    ['list', 'send', 'stream', 'toolRunner'],
    { toolRunner: 'managed_session_tool_runner_matrix_e2e.mjs' }),
  ...group('sessions.resources', '/v1/sessions/{session_id}/resources',
    'managed_resource_lifecycle_e2e.mjs', ['retrieve', 'update', 'list', 'delete', 'add'],
    { update: 'managed_session_resource_rotation_e2e.mjs' }),
  ...group('sessions.threads', '/v1/sessions/{session_id}/threads',
    'management_session_threads_e2e.mjs', ['retrieve', 'list', 'archive']),
  ...group('sessions.threads.events', '/v1/sessions/{session_id}/threads/{thread_id}/events',
    'management_session_threads_e2e.mjs', ['list', 'stream']),
  ...group('deployments', '/v1/deployments', 'management_deployments_e2e.mjs',
    ['create', 'retrieve', 'update', 'list', 'archive', 'pause', 'run', 'unpause']),
  ...group('deploymentRuns', '/v1/deployment_runs', 'management_deployments_e2e.mjs',
    ['retrieve', 'list']),
  ...group('vaults', '/v1/vaults', 'management_vaults_family_e2e.mjs',
    ['create', 'retrieve', 'update', 'list', 'delete', 'archive'],
    { retrieve: 'management_vaults_e2e.mjs', delete: 'management_vaults_e2e.mjs' }),
  ...group('vaults.credentials', '/v1/vaults/{vault_id}/credentials',
    'management_vaults_family_e2e.mjs',
    ['create', 'retrieve', 'update', 'list', 'delete', 'archive', 'mcpOAuthValidate'],
    { mcpOAuthValidate: 'management_vaults_e2e.mjs' }),
  ...group('memoryStores', '/v1/memory_stores', 'management_memory_stores_e2e.mjs',
    ['create', 'retrieve', 'update', 'list', 'delete', 'archive']),
  ...group('memoryStores.memories', '/v1/memory_stores/{memory_store_id}/memories',
    'management_memory_stores_e2e.mjs', ['create', 'retrieve', 'update', 'list', 'delete']),
  ...group('memoryStores.memoryVersions', '/v1/memory_stores/{memory_store_id}/memory_versions',
    'management_memory_stores_e2e.mjs', ['retrieve', 'list', 'redact']),
  ...group('files', '/v1/files', 'management_files_models_e2e.mjs',
    ['list', 'delete', 'download', 'retrieveMetadata', 'upload'],
    {
      list: 'managed_resources_api_e2e.mjs',
      download: 'managed_resources_api_e2e.mjs',
      retrieveMetadata: 'managed_full_lifecycle_e2e.mjs',
    }),
  ...group('skills', '/v1/skills', 'management_skills_e2e.mjs',
    ['create', 'retrieve', 'list', 'delete']),
  ...group('skills.versions', '/v1/skills/{skill_id}/versions', 'management_skills_e2e.mjs',
    ['create', 'retrieve', 'list', 'delete', 'download']),
  ...group('webhooks', 'offline-standard-webhooks', 'managed_webhooks_official_sdk_e2e.mjs', ['unwrap']),
  ...group('userProfiles', '/v1/user_profiles', 'management_user_profiles_e2e.mjs',
    ['create', 'retrieve', 'update', 'list', 'createEnrollmentURL']),
  ...group('dreams', '/v1/dreams', 'managed_dream_e2e.ts',
    ['create', 'retrieve', 'list', 'archive', 'cancel']),
  ...group('tunnels', '/v1/tunnels', 'management_tunnels_contract_e2e.mjs',
    ['create', 'retrieve', 'list', 'archive', 'revealToken', 'rotateToken']),
  ...group('tunnels.certificates', '/v1/tunnels/{tunnel_id}/certificates',
    'management_tunnels_contract_e2e.mjs', ['create', 'retrieve', 'list', 'archive']),
].sort((a, b) => a.sdkMethod.localeCompare(b.sdkMethod));
