#!/usr/bin/env bash
# Generate the management-plane TS contract from the Rust DTOs (ADR-0043),
# mirroring oversight-next's pipeline:
#   Rust #[derive(JsonSchema)]  ->  export_schemas (JSON Schema SSOT)  ->  TS types.
#
# We generate TS only for OUR surfaces (admin config API). The Managed Agents wire
# is the official @anthropic-ai/sdk — never regenerated here.
#
#   scripts/contract/generate-contracts.sh          # regenerate committed artifacts
#   scripts/contract/generate-contracts.sh --check   # fail if committed artifacts are stale
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
out_dir="$repo_root/contracts"
schema_json="$out_dir/model-schemas.generated.json"
openapi_json="$out_dir/openapi.generated.json"
ts_out="$out_dir/model-config.d.ts"
model_selection_ts="$out_dir/model-selection.generated.d.ts"
check=0
[ "${1:-}" = "--check" ] && check=1

mkdir -p "$out_dir"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# 1. JSON Schema SSOT from the Rust DTOs, plus the OpenAPI 3.1 document (route
#    registry over the same schemas; drives frontend openapi-typescript codegen).
cargo run --locked -q -p awaken-admin-config-api --features schema --example export_schemas \
    > "$tmp/schemas.json"
cargo run --locked -q -p awaken-admin-config-api --features schema --example export_openapi \
    > "$tmp/openapi.generated.json"

# 2. TS types via quicktype, if node tooling is available. Split the bundle into
#    one file per type so quicktype emits a single deduped .d.ts.
generated_ts=0
if command -v npx >/dev/null 2>&1; then
    # The WindowsApps `python3.exe` shim is discoverable but not executable from
    # Git Bash. Prefer the real `python.exe` on Windows; elsewhere retain the
    # conventional python3-first lookup.
    if [[ "${OSTYPE:-}" == msys* || "${OSTYPE:-}" == cygwin* ]]; then
        python_bin=python
    elif command -v python3 >/dev/null 2>&1; then
        python_bin=python3
    else
        python_bin=python
    fi
    "$python_bin" - "$tmp/schemas.json" "$tmp/split" <<'PY'
import json, os, sys
data = json.load(open(sys.argv[1], encoding="utf-8"))
os.makedirs(sys.argv[2], exist_ok=True)
for name, schema in data["schemas"].items():
    schema.setdefault("title", name)
    with open(os.path.join(sys.argv[2], f"{name}.json"), "w", encoding="utf-8") as handle:
        json.dump(schema, handle, ensure_ascii=False)
PY
    if npx --yes quicktype --quiet -s schema --lang typescript --just-types \
        --prefer-unions -o "$tmp/model-config.d.ts" "$tmp"/split/*.json 2>/dev/null; then
        printf '// GENERATED by scripts/contract/generate-contracts.sh — do not edit.\n' \
            > "$tmp/final.d.ts"
        cat "$tmp/model-config.d.ts" >> "$tmp/final.d.ts"
        generated_ts=1
    else
        echo "warn: quicktype unavailable/failed; emitting JSON Schema only" >&2
    fi
    if [ "$generated_ts" = 1 ]; then
        npx --yes json-schema-to-typescript \
            "$tmp/split/ModelSelection.json" \
            --output "$tmp/model-selection.generated.d.ts" >/dev/null
        "$python_bin" - "$tmp/model-selection.generated.d.ts" <<'PY'
import pathlib, sys
path = pathlib.Path(sys.argv[1])
text = path.read_text(encoding="utf-8")
# json-schema-to-typescript currently emits a suffixed duplicate when two
# discriminated branches reference the same $defs entry. Collapse that
# mechanical duplication; the JSON Schema remains the sole contract authority.
needle = "export interface AcpSessionConfiguration1"
if needle in text:
    start = text.rfind("/**", 0, text.index(needle))
    body = text.index("{", text.index(needle))
    depth = 0
    end = body
    while end < len(text):
        if text[end] == "{":
            depth += 1
        elif text[end] == "}":
            depth -= 1
            if depth == 0:
                end += 1
                break
        end += 1
    text = text[:start] + text[end:].lstrip("\n")
    text = text.replace("AcpSessionConfiguration1", "AcpSessionConfiguration")
path.write_text(text, encoding="utf-8")
PY
        sed -i '1i// GENERATED by scripts/contract/generate-contracts.sh — do not edit.' \
            "$tmp/model-selection.generated.d.ts"
    fi
else
    echo "warn: npx not found; emitting JSON Schema only" >&2
fi

if [ "$check" = 1 ]; then
    diff -u "$schema_json" "$tmp/schemas.json" >/dev/null \
        || { echo "✗ $schema_json is stale — run scripts/contract/generate-contracts.sh"; exit 1; }
    diff -u "$openapi_json" "$tmp/openapi.generated.json" >/dev/null \
        || { echo "✗ $openapi_json is stale — run scripts/contract/generate-contracts.sh"; exit 1; }
    if [ "$generated_ts" = 1 ]; then
        diff -u "$ts_out" "$tmp/final.d.ts" >/dev/null \
            || { echo "✗ $ts_out is stale — run scripts/contract/generate-contracts.sh"; exit 1; }
        diff -u "$model_selection_ts" "$tmp/model-selection.generated.d.ts" >/dev/null \
            || { echo "✗ $model_selection_ts is stale — run scripts/contract/generate-contracts.sh"; exit 1; }
    fi
    echo "OK - contracts up to date."
else
    cp "$tmp/schemas.json" "$schema_json"
    cp "$tmp/openapi.generated.json" "$openapi_json"
    [ "$generated_ts" = 1 ] && cp "$tmp/final.d.ts" "$ts_out"
    [ "$generated_ts" = 1 ] && cp "$tmp/model-selection.generated.d.ts" "$model_selection_ts"
    echo "wrote $schema_json + $openapi_json$([ "$generated_ts" = 1 ] && echo " + $ts_out + $model_selection_ts")"
fi
