#!/usr/bin/env bash
# Generate the management-plane TS contract from the Rust DTOs (ADR-0043),
# mirroring oversight-next's pipeline:
#   Rust #[derive(JsonSchema)]  ->  export_schemas (JSON Schema SSOT)  ->  TS types.
#
# We generate TS only for OUR surfaces (admin config API). The Managed Agents wire
# is the official @anthropic-ai/sdk — never regenerated here.
#
#   scripts/contract/generate-contracts.sh          # regenerate committed artifacts
#   scripts/contract/generate-contracts.sh --check   # fail if committed artifacts are stale
set -euo pipefail

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
out_dir="$repo_root/contracts"
schema_json="$out_dir/model-schemas.generated.json"
openapi_json="$out_dir/openapi.generated.json"
ts_out="$out_dir/model-config.d.ts"
check=0
[ "${1:-}" = "--check" ] && check=1

mkdir -p "$out_dir"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

# 1. JSON Schema SSOT from the Rust DTOs, plus the OpenAPI 3.1 document (route
#    registry over the same schemas; drives frontend openapi-typescript codegen).
cargo run --locked -q -p awaken-admin-config-api --features schema --example export_schemas \
    > "$tmp/schemas.json"
cargo run --locked -q -p awaken-admin-config-api --features schema --example export_openapi \
    > "$tmp/openapi.generated.json"

# 2. TS types via quicktype, if node tooling is available. Split the bundle into
#    one file per type so quicktype emits a single deduped .d.ts.
generated_ts=0
if command -v npx >/dev/null 2>&1; then
    python3 - "$tmp/schemas.json" "$tmp/split" <<'PY'
import json, os, sys
data = json.load(open(sys.argv[1]))
os.makedirs(sys.argv[2], exist_ok=True)
for name, schema in data["schemas"].items():
    schema.setdefault("title", name)
    json.dump(schema, open(os.path.join(sys.argv[2], f"{name}.json"), "w"))
PY
    if npx --yes quicktype --quiet -s schema --lang typescript --just-types \
        --prefer-unions -o "$tmp/model-config.d.ts" "$tmp"/split/*.json 2>/dev/null; then
        printf '// GENERATED by scripts/contract/generate-contracts.sh — do not edit.\n' \
            > "$tmp/final.d.ts"
        cat "$tmp/model-config.d.ts" >> "$tmp/final.d.ts"
        generated_ts=1
    else
        echo "warn: quicktype unavailable/failed; emitting JSON Schema only" >&2
    fi
else
    echo "warn: npx not found; emitting JSON Schema only" >&2
fi

if [ "$check" = 1 ]; then
    diff -u "$schema_json" "$tmp/schemas.json" >/dev/null \
        || { echo "✗ $schema_json is stale — run scripts/contract/generate-contracts.sh"; exit 1; }
    diff -u "$openapi_json" "$tmp/openapi.generated.json" >/dev/null \
        || { echo "✗ $openapi_json is stale — run scripts/contract/generate-contracts.sh"; exit 1; }
    if [ "$generated_ts" = 1 ]; then
        diff -u "$ts_out" "$tmp/final.d.ts" >/dev/null \
            || { echo "✗ $ts_out is stale — run scripts/contract/generate-contracts.sh"; exit 1; }
    fi
    echo "OK - contracts up to date."
else
    cp "$tmp/schemas.json" "$schema_json"
    cp "$tmp/openapi.generated.json" "$openapi_json"
    [ "$generated_ts" = 1 ] && cp "$tmp/final.d.ts" "$ts_out"
    echo "wrote $schema_json + $openapi_json$([ "$generated_ts" = 1 ] && echo " + $ts_out")"
fi
