//! Emit JSON Schema for the admin config-plane DTOs to stdout (ADR-0043). This is
//! the SSOT the TS contract is generated from (see `scripts/contract/
//! generate-contracts.sh`), mirroring oversight-next's `export_schemas`.
//!
//! The schema list itself lives in `awaken_admin_config_api::openapi::contract_schemas`,
//! shared with the OpenAPI document so the two artifacts cannot drift.
//!
//! ```sh
//! cargo run -p awaken-admin-config-api --features schema --example export_schemas
//! ```

use serde_json::{Value, json};

fn main() {
    let root = json!({
        "$comment": "GENERATED by awaken-admin-config-api export_schemas; do not edit.",
        "version": awaken_admin_config_api::API_VERSION,
        "schemas": Value::Object(awaken_admin_config_api::openapi::contract_schemas()),
    });
    println!(
        "{}",
        serde_json::to_string_pretty(&root).expect("root serializes")
    );
}
