name: Lint
on:
  push:
    branches: [main, master]
  pull_request:
concurrency:
  group: lint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  rustfmt:
    name: Rust Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.93.0
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Rust Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.93.0
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --workspace --lib --bins --examples --locked -- -D clippy::correctness
